import type {
  CrawloraGeneratedGroups,
  OperationId,
  OperationParamsMap,
  OperationRequestArgs,
  OperationResponseMap
} from "./types.js";

export type CrawloraParams = Record<string, unknown>;
export type CrawloraLogEvent = { event: string; [key: string]: unknown };
export interface CrawloraRequestContext { operationId: string; method: string; url: string; headers: Record<string, string> }
export type CrawloraBeforeRequest = (ctx: CrawloraRequestContext) => void | Promise<void>;
export type CrawloraAfterResponse = (operationId: string, status: number, headers: Record<string, string>, body: unknown) => unknown;

export interface CrawloraClientOptions {
  apiKey?: string;
  jwtToken?: string;
  baseUrl?: string;
  timeout?: number;
  retries?: number;
  retryDelay?: number;
  maxRetryDelay?: number;
  retryStatuses?: Iterable<number>;
  isRetryable?: (status: number, error: CrawloraError) => boolean;
  onRetry?: (attempt: number, error: CrawloraError, delay: number) => void;
  requestId?: boolean;
  idempotencyKeys?: boolean;
  rateLimit?: number;
  maxConcurrency?: number;
  logger?: (event: CrawloraLogEvent) => void;
  beforeRequest?: CrawloraBeforeRequest | Iterable<CrawloraBeforeRequest>;
  afterResponse?: CrawloraAfterResponse | Iterable<CrawloraAfterResponse>;
  headers?: Record<string, string>;
  userAgent?: string | false;
  fetch?: typeof globalThis.fetch;
}

export interface CrawloraRequestOptions {
  headers?: Record<string, string>;
  responseType?: "auto" | "json" | "text" | "stream";
  timeout?: number;
  signal?: AbortSignal;
  retries?: number;
  isRetryable?: (status: number, error: CrawloraError) => boolean;
}

export interface OperationDefinition {
  id: string; method: string; path: string; pathParams: string[];
  queryParams: Array<{ name: string; in?: "query"; collectionFormat?: string; type?: string; required?: boolean; enum?: string[] }>;
  formParams: Array<{ name: string; in?: "formData"; type?: string; required?: boolean; enum?: string[] }>;
  bodyParam?: string; bodyRequired?: boolean; consumes: string[]; produces: string[]; security: string[];
  paginatable?: boolean; cursorParams?: string[];
}

export class CrawloraError extends Error {
  status: number; code?: number; body: unknown; headers: Record<string, string>;
  response?: Response; cause?: unknown; retryable?: boolean; requestId?: string;
}
export class CrawloraClientError extends CrawloraError {}
export class CrawloraServerError extends CrawloraError {}
export class CrawloraNetworkError extends CrawloraError {}

export interface CrawloraPaginateOptions extends CrawloraRequestOptions {
  pageParam?: string; cursorParam?: string; nextCursor?: (page: unknown) => unknown;
  start?: unknown; step?: number; maxPages?: number;
}
export interface CrawloraPaginateItemsOptions extends CrawloraPaginateOptions {
  items?: (page: unknown) => Iterable<unknown>;
}

export class CrawloraClient {
  constructor(options?: CrawloraClientOptions);
  request<I extends OperationId>(operationId: I, params: OperationParamsMap[I], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  request<I extends OperationId>(operationId: I, params: OperationParamsMap[I], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  request<I extends OperationId>(operationId: I, ...args: OperationRequestArgs<I>): Promise<OperationResponseMap[I]>;
  operation<I extends OperationId>(operationId: I, params: OperationParamsMap[I], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  operation<I extends OperationId>(operationId: I, params: OperationParamsMap[I], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  operation<I extends OperationId>(operationId: I, ...args: OperationRequestArgs<I>): Promise<OperationResponseMap[I]>;
  paginate<I extends OperationId>(operationId: I, params?: OperationParamsMap[I], options?: CrawloraPaginateOptions): AsyncGenerator<OperationResponseMap[I], void, unknown>;
  paginateItems<I extends OperationId>(operationId: I, params?: OperationParamsMap[I], options?: CrawloraPaginateItemsOptions): AsyncGenerator<unknown, void, unknown>;
  [group: string]: unknown;
}
export interface CrawloraClient extends CrawloraGeneratedGroups {}

export class SofascoreClient extends CrawloraClient {
  request<I extends OperationId>(operationId: I, params: OperationParamsMap[I], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  operation<I extends OperationId>(operationId: I, params: OperationParamsMap[I], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  categories(params: OperationParamsMap["sofascore-categories"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  categoryTournaments(params: OperationParamsMap["sofascore-category-tournaments"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  draft(params: OperationParamsMap["sofascore-draft"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  draftPicks(params: OperationParamsMap["sofascore-draft-picks"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  esportsGame(params: OperationParamsMap["sofascore-esports-game"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  event(params: OperationParamsMap["sofascore-event"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventAtBatPitches(params: OperationParamsMap["sofascore-event-at-bat-pitches"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventAtBats(params: OperationParamsMap["sofascore-event-at-bats"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventAveragePositions(params: OperationParamsMap["sofascore-event-average-positions"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventBaseballTopPerformers(params: OperationParamsMap["sofascore-event-baseball-top-performers"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventBestPlayers(params: OperationParamsMap["sofascore-event-best-players"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventComments(params: OperationParamsMap["sofascore-event-comments"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventEsportsGames(params: OperationParamsMap["sofascore-event-esports-games"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventGraph(params: OperationParamsMap["sofascore-event-graph"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventH2h(params: OperationParamsMap["sofascore-event-h2h"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventHighlights(params: OperationParamsMap["sofascore-event-highlights"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventIncidents(params: OperationParamsMap["sofascore-event-incidents"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventInnings(params: OperationParamsMap["sofascore-event-innings"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventLineups(params: OperationParamsMap["sofascore-event-lineups"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventManagers(params: OperationParamsMap["sofascore-event-managers"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventOdds(params: OperationParamsMap["sofascore-event-odds"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventPlayerHeatmap(params: OperationParamsMap["sofascore-event-player-heatmap"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventPlayerStatistics(params: OperationParamsMap["sofascore-event-player-statistics"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventPointByPoint(params: OperationParamsMap["sofascore-event-point-by-point"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventPregameForm(params: OperationParamsMap["sofascore-event-pregame-form"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventShotmap(params: OperationParamsMap["sofascore-event-shotmap"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventStatistics(params: OperationParamsMap["sofascore-event-statistics"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventTeamHeatmap(params: OperationParamsMap["sofascore-event-team-heatmap"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventTeamStreaks(params: OperationParamsMap["sofascore-event-team-streaks"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventTennisPower(params: OperationParamsMap["sofascore-event-tennis-power"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventTvChannels(params: OperationParamsMap["sofascore-event-tv-channels"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  eventVotes(params: OperationParamsMap["sofascore-event-votes"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  liveEvents(params: OperationParamsMap["sofascore-live-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  manager(params: OperationParamsMap["sofascore-manager"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  managerEvents(params: OperationParamsMap["sofascore-manager-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  mmaCard(params: OperationParamsMap["sofascore-mma-card"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  mmaSchedule(params: OperationParamsMap["sofascore-mma-schedule"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  oddsDropping(params?: OperationParamsMap["sofascore-odds-dropping"], options?: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  oddsWinning(params?: OperationParamsMap["sofascore-odds-winning"], options?: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  player(params: OperationParamsMap["sofascore-player"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerAttributes(params: OperationParamsMap["sofascore-player-attributes"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerEvents(params: OperationParamsMap["sofascore-player-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerLastYearSummary(params: OperationParamsMap["sofascore-player-last-year-summary"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerNationalTeamStatistics(params: OperationParamsMap["sofascore-player-national-team-statistics"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerPenaltyHistory(params: OperationParamsMap["sofascore-player-penalty-history"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerRatings(params: OperationParamsMap["sofascore-player-ratings"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerSeasonHeatmap(params: OperationParamsMap["sofascore-player-season-heatmap"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerSeasonStatistics(params: OperationParamsMap["sofascore-player-season-statistics"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerStatisticalRankings(params: OperationParamsMap["sofascore-player-statistical-rankings"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerStatisticsSeasons(params: OperationParamsMap["sofascore-player-statistics-seasons"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerTournaments(params: OperationParamsMap["sofascore-player-tournaments"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  playerTransfers(params: OperationParamsMap["sofascore-player-transfers"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  rankingTypes(params?: OperationParamsMap["sofascore-ranking-types"], options?: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  rankings(params: OperationParamsMap["sofascore-rankings"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  referee(params: OperationParamsMap["sofascore-referee"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  refereeEvents(params: OperationParamsMap["sofascore-referee-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  refereeStatistics(params: OperationParamsMap["sofascore-referee-statistics"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  roundEvents(params: OperationParamsMap["sofascore-round-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  scheduledEvents(params: OperationParamsMap["sofascore-scheduled-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  scheduledTournaments(params: OperationParamsMap["sofascore-scheduled-tournaments"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  search(params: OperationParamsMap["sofascore-search"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  searchTyped(params: OperationParamsMap["sofascore-search-typed"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  seasonEvents(params: OperationParamsMap["sofascore-season-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  sports(params?: OperationParamsMap["sofascore-sports"], options?: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  stage(params: OperationParamsMap["sofascore-stage"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  stageCategories(params: OperationParamsMap["sofascore-stage-categories"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  stageDriverPerformance(params: OperationParamsMap["sofascore-stage-driver-performance"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  stageFeatured(params: OperationParamsMap["sofascore-stage-featured"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  stageSchedule(params: OperationParamsMap["sofascore-stage-schedule"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  stageSeasons(params: OperationParamsMap["sofascore-stage-seasons"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  stageStandings(params: OperationParamsMap["sofascore-stage-standings"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  stageSubstages(params: OperationParamsMap["sofascore-stage-substages"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  standings(params: OperationParamsMap["sofascore-standings"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  team(params: OperationParamsMap["sofascore-team"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamAchievements(params: OperationParamsMap["sofascore-team-achievements"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamEvents(params: OperationParamsMap["sofascore-team-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamGoalDistributions(params: OperationParamsMap["sofascore-team-goal-distributions"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamNearEvents(params: OperationParamsMap["sofascore-team-near-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamOfTheWeek(params: OperationParamsMap["sofascore-team-of-the-week"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamOfTheWeekPeriods(params: OperationParamsMap["sofascore-team-of-the-week-periods"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamPerformance(params: OperationParamsMap["sofascore-team-performance"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamPlayerStatistics(params: OperationParamsMap["sofascore-team-player-statistics"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamPlayerStatisticsSeasons(params: OperationParamsMap["sofascore-team-player-statistics-seasons"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamPlayers(params: OperationParamsMap["sofascore-team-players"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamRankings(params: OperationParamsMap["sofascore-team-rankings"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamSeasonStatistics(params: OperationParamsMap["sofascore-team-season-statistics"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamStatisticsSeasons(params: OperationParamsMap["sofascore-team-statistics-seasons"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamTopPlayers(params: OperationParamsMap["sofascore-team-top-players"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamTournaments(params: OperationParamsMap["sofascore-team-tournaments"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  teamTransfers(params: OperationParamsMap["sofascore-team-transfers"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tennisPlayerGrandSlamResults(params: OperationParamsMap["sofascore-tennis-player-grand-slam-results"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentCuptree(params: OperationParamsMap["sofascore-tournament-cuptree"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentInfo(params: OperationParamsMap["sofascore-tournament-info"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentPlayerOfTheSeason(params: OperationParamsMap["sofascore-tournament-player-of-the-season"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentPlayerStatistics(params: OperationParamsMap["sofascore-tournament-player-statistics"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentRounds(params: OperationParamsMap["sofascore-tournament-rounds"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentSeasons(params: OperationParamsMap["sofascore-tournament-seasons"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentStatisticsInfo(params: OperationParamsMap["sofascore-tournament-statistics-info"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentTeamOfTheSeason(params: OperationParamsMap["sofascore-tournament-team-of-the-season"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentTeams(params: OperationParamsMap["sofascore-tournament-teams"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentTopPlayers(params: OperationParamsMap["sofascore-tournament-top-players"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentTopTeams(params: OperationParamsMap["sofascore-tournament-top-teams"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentVenues(params: OperationParamsMap["sofascore-tournament-venues"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentWinners(params: OperationParamsMap["sofascore-tournament-winners"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  tournamentsWithFeature(params: OperationParamsMap["sofascore-tournaments-with-feature"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  trendingEvents(params: OperationParamsMap["sofascore-trending-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  trendingPlayers(params: OperationParamsMap["sofascore-trending-players"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  venue(params: OperationParamsMap["sofascore-venue"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  venueEvents(params: OperationParamsMap["sofascore-venue-events"], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  request<I extends OperationId>(operationId: I, params: OperationParamsMap[I], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  operation<I extends OperationId>(operationId: I, params: OperationParamsMap[I], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  categories(params: OperationParamsMap["sofascore-categories"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  categoryTournaments(params: OperationParamsMap["sofascore-category-tournaments"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  draft(params: OperationParamsMap["sofascore-draft"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  draftPicks(params: OperationParamsMap["sofascore-draft-picks"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  esportsGame(params: OperationParamsMap["sofascore-esports-game"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  event(params: OperationParamsMap["sofascore-event"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventAtBatPitches(params: OperationParamsMap["sofascore-event-at-bat-pitches"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventAtBats(params: OperationParamsMap["sofascore-event-at-bats"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventAveragePositions(params: OperationParamsMap["sofascore-event-average-positions"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventBaseballTopPerformers(params: OperationParamsMap["sofascore-event-baseball-top-performers"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventBestPlayers(params: OperationParamsMap["sofascore-event-best-players"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventComments(params: OperationParamsMap["sofascore-event-comments"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventEsportsGames(params: OperationParamsMap["sofascore-event-esports-games"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventGraph(params: OperationParamsMap["sofascore-event-graph"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventH2h(params: OperationParamsMap["sofascore-event-h2h"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventHighlights(params: OperationParamsMap["sofascore-event-highlights"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventIncidents(params: OperationParamsMap["sofascore-event-incidents"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventInnings(params: OperationParamsMap["sofascore-event-innings"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventLineups(params: OperationParamsMap["sofascore-event-lineups"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventManagers(params: OperationParamsMap["sofascore-event-managers"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventOdds(params: OperationParamsMap["sofascore-event-odds"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventPlayerHeatmap(params: OperationParamsMap["sofascore-event-player-heatmap"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventPlayerStatistics(params: OperationParamsMap["sofascore-event-player-statistics"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventPointByPoint(params: OperationParamsMap["sofascore-event-point-by-point"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventPregameForm(params: OperationParamsMap["sofascore-event-pregame-form"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventShotmap(params: OperationParamsMap["sofascore-event-shotmap"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventStatistics(params: OperationParamsMap["sofascore-event-statistics"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventTeamHeatmap(params: OperationParamsMap["sofascore-event-team-heatmap"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventTeamStreaks(params: OperationParamsMap["sofascore-event-team-streaks"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventTennisPower(params: OperationParamsMap["sofascore-event-tennis-power"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventTvChannels(params: OperationParamsMap["sofascore-event-tv-channels"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  eventVotes(params: OperationParamsMap["sofascore-event-votes"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  liveEvents(params: OperationParamsMap["sofascore-live-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  manager(params: OperationParamsMap["sofascore-manager"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  managerEvents(params: OperationParamsMap["sofascore-manager-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  mmaCard(params: OperationParamsMap["sofascore-mma-card"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  mmaSchedule(params: OperationParamsMap["sofascore-mma-schedule"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  oddsDropping(params?: OperationParamsMap["sofascore-odds-dropping"], options?: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  oddsWinning(params?: OperationParamsMap["sofascore-odds-winning"], options?: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  player(params: OperationParamsMap["sofascore-player"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerAttributes(params: OperationParamsMap["sofascore-player-attributes"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerEvents(params: OperationParamsMap["sofascore-player-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerLastYearSummary(params: OperationParamsMap["sofascore-player-last-year-summary"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerNationalTeamStatistics(params: OperationParamsMap["sofascore-player-national-team-statistics"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerPenaltyHistory(params: OperationParamsMap["sofascore-player-penalty-history"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerRatings(params: OperationParamsMap["sofascore-player-ratings"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerSeasonHeatmap(params: OperationParamsMap["sofascore-player-season-heatmap"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerSeasonStatistics(params: OperationParamsMap["sofascore-player-season-statistics"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerStatisticalRankings(params: OperationParamsMap["sofascore-player-statistical-rankings"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerStatisticsSeasons(params: OperationParamsMap["sofascore-player-statistics-seasons"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerTournaments(params: OperationParamsMap["sofascore-player-tournaments"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  playerTransfers(params: OperationParamsMap["sofascore-player-transfers"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  rankingTypes(params?: OperationParamsMap["sofascore-ranking-types"], options?: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  rankings(params: OperationParamsMap["sofascore-rankings"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  referee(params: OperationParamsMap["sofascore-referee"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  refereeEvents(params: OperationParamsMap["sofascore-referee-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  refereeStatistics(params: OperationParamsMap["sofascore-referee-statistics"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  roundEvents(params: OperationParamsMap["sofascore-round-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  scheduledEvents(params: OperationParamsMap["sofascore-scheduled-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  scheduledTournaments(params: OperationParamsMap["sofascore-scheduled-tournaments"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  search(params: OperationParamsMap["sofascore-search"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  searchTyped(params: OperationParamsMap["sofascore-search-typed"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  seasonEvents(params: OperationParamsMap["sofascore-season-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  sports(params?: OperationParamsMap["sofascore-sports"], options?: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  stage(params: OperationParamsMap["sofascore-stage"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  stageCategories(params: OperationParamsMap["sofascore-stage-categories"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  stageDriverPerformance(params: OperationParamsMap["sofascore-stage-driver-performance"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  stageFeatured(params: OperationParamsMap["sofascore-stage-featured"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  stageSchedule(params: OperationParamsMap["sofascore-stage-schedule"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  stageSeasons(params: OperationParamsMap["sofascore-stage-seasons"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  stageStandings(params: OperationParamsMap["sofascore-stage-standings"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  stageSubstages(params: OperationParamsMap["sofascore-stage-substages"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  standings(params: OperationParamsMap["sofascore-standings"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  team(params: OperationParamsMap["sofascore-team"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamAchievements(params: OperationParamsMap["sofascore-team-achievements"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamEvents(params: OperationParamsMap["sofascore-team-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamGoalDistributions(params: OperationParamsMap["sofascore-team-goal-distributions"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamNearEvents(params: OperationParamsMap["sofascore-team-near-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamOfTheWeek(params: OperationParamsMap["sofascore-team-of-the-week"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamOfTheWeekPeriods(params: OperationParamsMap["sofascore-team-of-the-week-periods"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamPerformance(params: OperationParamsMap["sofascore-team-performance"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamPlayerStatistics(params: OperationParamsMap["sofascore-team-player-statistics"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamPlayerStatisticsSeasons(params: OperationParamsMap["sofascore-team-player-statistics-seasons"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamPlayers(params: OperationParamsMap["sofascore-team-players"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamRankings(params: OperationParamsMap["sofascore-team-rankings"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamSeasonStatistics(params: OperationParamsMap["sofascore-team-season-statistics"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamStatisticsSeasons(params: OperationParamsMap["sofascore-team-statistics-seasons"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamTopPlayers(params: OperationParamsMap["sofascore-team-top-players"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamTournaments(params: OperationParamsMap["sofascore-team-tournaments"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  teamTransfers(params: OperationParamsMap["sofascore-team-transfers"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tennisPlayerGrandSlamResults(params: OperationParamsMap["sofascore-tennis-player-grand-slam-results"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentCuptree(params: OperationParamsMap["sofascore-tournament-cuptree"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentInfo(params: OperationParamsMap["sofascore-tournament-info"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentPlayerOfTheSeason(params: OperationParamsMap["sofascore-tournament-player-of-the-season"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentPlayerStatistics(params: OperationParamsMap["sofascore-tournament-player-statistics"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentRounds(params: OperationParamsMap["sofascore-tournament-rounds"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentSeasons(params: OperationParamsMap["sofascore-tournament-seasons"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentStatisticsInfo(params: OperationParamsMap["sofascore-tournament-statistics-info"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentTeamOfTheSeason(params: OperationParamsMap["sofascore-tournament-team-of-the-season"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentTeams(params: OperationParamsMap["sofascore-tournament-teams"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentTopPlayers(params: OperationParamsMap["sofascore-tournament-top-players"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentTopTeams(params: OperationParamsMap["sofascore-tournament-top-teams"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentVenues(params: OperationParamsMap["sofascore-tournament-venues"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentWinners(params: OperationParamsMap["sofascore-tournament-winners"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  tournamentsWithFeature(params: OperationParamsMap["sofascore-tournaments-with-feature"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  trendingEvents(params: OperationParamsMap["sofascore-trending-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  trendingPlayers(params: OperationParamsMap["sofascore-trending-players"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  venue(params: OperationParamsMap["sofascore-venue"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;
  venueEvents(params: OperationParamsMap["sofascore-venue-events"], options: CrawloraRequestOptions & { responseType: "text" }): Promise<string>;

  request<I extends OperationId>(operationId: I, params: OperationParamsMap[I], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  request<I extends OperationId>(operationId: I, ...args: OperationRequestArgs<I>): Promise<OperationResponseMap[I]>;
  operation<I extends OperationId>(operationId: I, params: OperationParamsMap[I], options: CrawloraRequestOptions & { responseType: "stream" }): Promise<Response>;
  operation<I extends OperationId>(operationId: I, ...args: OperationRequestArgs<I>): Promise<OperationResponseMap[I]>;
  categories(...args: OperationRequestArgs<"sofascore-categories">): Promise<OperationResponseMap["sofascore-categories"]>;
  categoryTournaments(...args: OperationRequestArgs<"sofascore-category-tournaments">): Promise<OperationResponseMap["sofascore-category-tournaments"]>;
  draft(...args: OperationRequestArgs<"sofascore-draft">): Promise<OperationResponseMap["sofascore-draft"]>;
  draftPicks(...args: OperationRequestArgs<"sofascore-draft-picks">): Promise<OperationResponseMap["sofascore-draft-picks"]>;
  esportsGame(...args: OperationRequestArgs<"sofascore-esports-game">): Promise<OperationResponseMap["sofascore-esports-game"]>;
  event(...args: OperationRequestArgs<"sofascore-event">): Promise<OperationResponseMap["sofascore-event"]>;
  eventAtBatPitches(...args: OperationRequestArgs<"sofascore-event-at-bat-pitches">): Promise<OperationResponseMap["sofascore-event-at-bat-pitches"]>;
  eventAtBats(...args: OperationRequestArgs<"sofascore-event-at-bats">): Promise<OperationResponseMap["sofascore-event-at-bats"]>;
  eventAveragePositions(...args: OperationRequestArgs<"sofascore-event-average-positions">): Promise<OperationResponseMap["sofascore-event-average-positions"]>;
  eventBaseballTopPerformers(...args: OperationRequestArgs<"sofascore-event-baseball-top-performers">): Promise<OperationResponseMap["sofascore-event-baseball-top-performers"]>;
  eventBestPlayers(...args: OperationRequestArgs<"sofascore-event-best-players">): Promise<OperationResponseMap["sofascore-event-best-players"]>;
  eventComments(...args: OperationRequestArgs<"sofascore-event-comments">): Promise<OperationResponseMap["sofascore-event-comments"]>;
  eventEsportsGames(...args: OperationRequestArgs<"sofascore-event-esports-games">): Promise<OperationResponseMap["sofascore-event-esports-games"]>;
  eventGraph(...args: OperationRequestArgs<"sofascore-event-graph">): Promise<OperationResponseMap["sofascore-event-graph"]>;
  eventH2h(...args: OperationRequestArgs<"sofascore-event-h2h">): Promise<OperationResponseMap["sofascore-event-h2h"]>;
  eventHighlights(...args: OperationRequestArgs<"sofascore-event-highlights">): Promise<OperationResponseMap["sofascore-event-highlights"]>;
  eventIncidents(...args: OperationRequestArgs<"sofascore-event-incidents">): Promise<OperationResponseMap["sofascore-event-incidents"]>;
  eventInnings(...args: OperationRequestArgs<"sofascore-event-innings">): Promise<OperationResponseMap["sofascore-event-innings"]>;
  eventLineups(...args: OperationRequestArgs<"sofascore-event-lineups">): Promise<OperationResponseMap["sofascore-event-lineups"]>;
  eventManagers(...args: OperationRequestArgs<"sofascore-event-managers">): Promise<OperationResponseMap["sofascore-event-managers"]>;
  eventOdds(...args: OperationRequestArgs<"sofascore-event-odds">): Promise<OperationResponseMap["sofascore-event-odds"]>;
  eventPlayerHeatmap(...args: OperationRequestArgs<"sofascore-event-player-heatmap">): Promise<OperationResponseMap["sofascore-event-player-heatmap"]>;
  eventPlayerStatistics(...args: OperationRequestArgs<"sofascore-event-player-statistics">): Promise<OperationResponseMap["sofascore-event-player-statistics"]>;
  eventPointByPoint(...args: OperationRequestArgs<"sofascore-event-point-by-point">): Promise<OperationResponseMap["sofascore-event-point-by-point"]>;
  eventPregameForm(...args: OperationRequestArgs<"sofascore-event-pregame-form">): Promise<OperationResponseMap["sofascore-event-pregame-form"]>;
  eventShotmap(...args: OperationRequestArgs<"sofascore-event-shotmap">): Promise<OperationResponseMap["sofascore-event-shotmap"]>;
  eventStatistics(...args: OperationRequestArgs<"sofascore-event-statistics">): Promise<OperationResponseMap["sofascore-event-statistics"]>;
  eventTeamHeatmap(...args: OperationRequestArgs<"sofascore-event-team-heatmap">): Promise<OperationResponseMap["sofascore-event-team-heatmap"]>;
  eventTeamStreaks(...args: OperationRequestArgs<"sofascore-event-team-streaks">): Promise<OperationResponseMap["sofascore-event-team-streaks"]>;
  eventTennisPower(...args: OperationRequestArgs<"sofascore-event-tennis-power">): Promise<OperationResponseMap["sofascore-event-tennis-power"]>;
  eventTvChannels(...args: OperationRequestArgs<"sofascore-event-tv-channels">): Promise<OperationResponseMap["sofascore-event-tv-channels"]>;
  eventVotes(...args: OperationRequestArgs<"sofascore-event-votes">): Promise<OperationResponseMap["sofascore-event-votes"]>;
  liveEvents(...args: OperationRequestArgs<"sofascore-live-events">): Promise<OperationResponseMap["sofascore-live-events"]>;
  manager(...args: OperationRequestArgs<"sofascore-manager">): Promise<OperationResponseMap["sofascore-manager"]>;
  managerEvents(...args: OperationRequestArgs<"sofascore-manager-events">): Promise<OperationResponseMap["sofascore-manager-events"]>;
  mmaCard(...args: OperationRequestArgs<"sofascore-mma-card">): Promise<OperationResponseMap["sofascore-mma-card"]>;
  mmaSchedule(...args: OperationRequestArgs<"sofascore-mma-schedule">): Promise<OperationResponseMap["sofascore-mma-schedule"]>;
  oddsDropping(...args: OperationRequestArgs<"sofascore-odds-dropping">): Promise<OperationResponseMap["sofascore-odds-dropping"]>;
  oddsWinning(...args: OperationRequestArgs<"sofascore-odds-winning">): Promise<OperationResponseMap["sofascore-odds-winning"]>;
  player(...args: OperationRequestArgs<"sofascore-player">): Promise<OperationResponseMap["sofascore-player"]>;
  playerAttributes(...args: OperationRequestArgs<"sofascore-player-attributes">): Promise<OperationResponseMap["sofascore-player-attributes"]>;
  playerEvents(...args: OperationRequestArgs<"sofascore-player-events">): Promise<OperationResponseMap["sofascore-player-events"]>;
  playerLastYearSummary(...args: OperationRequestArgs<"sofascore-player-last-year-summary">): Promise<OperationResponseMap["sofascore-player-last-year-summary"]>;
  playerNationalTeamStatistics(...args: OperationRequestArgs<"sofascore-player-national-team-statistics">): Promise<OperationResponseMap["sofascore-player-national-team-statistics"]>;
  playerPenaltyHistory(...args: OperationRequestArgs<"sofascore-player-penalty-history">): Promise<OperationResponseMap["sofascore-player-penalty-history"]>;
  playerRatings(...args: OperationRequestArgs<"sofascore-player-ratings">): Promise<OperationResponseMap["sofascore-player-ratings"]>;
  playerSeasonHeatmap(...args: OperationRequestArgs<"sofascore-player-season-heatmap">): Promise<OperationResponseMap["sofascore-player-season-heatmap"]>;
  playerSeasonStatistics(...args: OperationRequestArgs<"sofascore-player-season-statistics">): Promise<OperationResponseMap["sofascore-player-season-statistics"]>;
  playerStatisticalRankings(...args: OperationRequestArgs<"sofascore-player-statistical-rankings">): Promise<OperationResponseMap["sofascore-player-statistical-rankings"]>;
  playerStatisticsSeasons(...args: OperationRequestArgs<"sofascore-player-statistics-seasons">): Promise<OperationResponseMap["sofascore-player-statistics-seasons"]>;
  playerTournaments(...args: OperationRequestArgs<"sofascore-player-tournaments">): Promise<OperationResponseMap["sofascore-player-tournaments"]>;
  playerTransfers(...args: OperationRequestArgs<"sofascore-player-transfers">): Promise<OperationResponseMap["sofascore-player-transfers"]>;
  rankingTypes(...args: OperationRequestArgs<"sofascore-ranking-types">): Promise<OperationResponseMap["sofascore-ranking-types"]>;
  rankings(...args: OperationRequestArgs<"sofascore-rankings">): Promise<OperationResponseMap["sofascore-rankings"]>;
  referee(...args: OperationRequestArgs<"sofascore-referee">): Promise<OperationResponseMap["sofascore-referee"]>;
  refereeEvents(...args: OperationRequestArgs<"sofascore-referee-events">): Promise<OperationResponseMap["sofascore-referee-events"]>;
  refereeStatistics(...args: OperationRequestArgs<"sofascore-referee-statistics">): Promise<OperationResponseMap["sofascore-referee-statistics"]>;
  roundEvents(...args: OperationRequestArgs<"sofascore-round-events">): Promise<OperationResponseMap["sofascore-round-events"]>;
  scheduledEvents(...args: OperationRequestArgs<"sofascore-scheduled-events">): Promise<OperationResponseMap["sofascore-scheduled-events"]>;
  scheduledTournaments(...args: OperationRequestArgs<"sofascore-scheduled-tournaments">): Promise<OperationResponseMap["sofascore-scheduled-tournaments"]>;
  search(...args: OperationRequestArgs<"sofascore-search">): Promise<OperationResponseMap["sofascore-search"]>;
  searchTyped(...args: OperationRequestArgs<"sofascore-search-typed">): Promise<OperationResponseMap["sofascore-search-typed"]>;
  seasonEvents(...args: OperationRequestArgs<"sofascore-season-events">): Promise<OperationResponseMap["sofascore-season-events"]>;
  sports(...args: OperationRequestArgs<"sofascore-sports">): Promise<OperationResponseMap["sofascore-sports"]>;
  stage(...args: OperationRequestArgs<"sofascore-stage">): Promise<OperationResponseMap["sofascore-stage"]>;
  stageCategories(...args: OperationRequestArgs<"sofascore-stage-categories">): Promise<OperationResponseMap["sofascore-stage-categories"]>;
  stageDriverPerformance(...args: OperationRequestArgs<"sofascore-stage-driver-performance">): Promise<OperationResponseMap["sofascore-stage-driver-performance"]>;
  stageFeatured(...args: OperationRequestArgs<"sofascore-stage-featured">): Promise<OperationResponseMap["sofascore-stage-featured"]>;
  stageSchedule(...args: OperationRequestArgs<"sofascore-stage-schedule">): Promise<OperationResponseMap["sofascore-stage-schedule"]>;
  stageSeasons(...args: OperationRequestArgs<"sofascore-stage-seasons">): Promise<OperationResponseMap["sofascore-stage-seasons"]>;
  stageStandings(...args: OperationRequestArgs<"sofascore-stage-standings">): Promise<OperationResponseMap["sofascore-stage-standings"]>;
  stageSubstages(...args: OperationRequestArgs<"sofascore-stage-substages">): Promise<OperationResponseMap["sofascore-stage-substages"]>;
  standings(...args: OperationRequestArgs<"sofascore-standings">): Promise<OperationResponseMap["sofascore-standings"]>;
  team(...args: OperationRequestArgs<"sofascore-team">): Promise<OperationResponseMap["sofascore-team"]>;
  teamAchievements(...args: OperationRequestArgs<"sofascore-team-achievements">): Promise<OperationResponseMap["sofascore-team-achievements"]>;
  teamEvents(...args: OperationRequestArgs<"sofascore-team-events">): Promise<OperationResponseMap["sofascore-team-events"]>;
  teamGoalDistributions(...args: OperationRequestArgs<"sofascore-team-goal-distributions">): Promise<OperationResponseMap["sofascore-team-goal-distributions"]>;
  teamNearEvents(...args: OperationRequestArgs<"sofascore-team-near-events">): Promise<OperationResponseMap["sofascore-team-near-events"]>;
  teamOfTheWeek(...args: OperationRequestArgs<"sofascore-team-of-the-week">): Promise<OperationResponseMap["sofascore-team-of-the-week"]>;
  teamOfTheWeekPeriods(...args: OperationRequestArgs<"sofascore-team-of-the-week-periods">): Promise<OperationResponseMap["sofascore-team-of-the-week-periods"]>;
  teamPerformance(...args: OperationRequestArgs<"sofascore-team-performance">): Promise<OperationResponseMap["sofascore-team-performance"]>;
  teamPlayerStatistics(...args: OperationRequestArgs<"sofascore-team-player-statistics">): Promise<OperationResponseMap["sofascore-team-player-statistics"]>;
  teamPlayerStatisticsSeasons(...args: OperationRequestArgs<"sofascore-team-player-statistics-seasons">): Promise<OperationResponseMap["sofascore-team-player-statistics-seasons"]>;
  teamPlayers(...args: OperationRequestArgs<"sofascore-team-players">): Promise<OperationResponseMap["sofascore-team-players"]>;
  teamRankings(...args: OperationRequestArgs<"sofascore-team-rankings">): Promise<OperationResponseMap["sofascore-team-rankings"]>;
  teamSeasonStatistics(...args: OperationRequestArgs<"sofascore-team-season-statistics">): Promise<OperationResponseMap["sofascore-team-season-statistics"]>;
  teamStatisticsSeasons(...args: OperationRequestArgs<"sofascore-team-statistics-seasons">): Promise<OperationResponseMap["sofascore-team-statistics-seasons"]>;
  teamTopPlayers(...args: OperationRequestArgs<"sofascore-team-top-players">): Promise<OperationResponseMap["sofascore-team-top-players"]>;
  teamTournaments(...args: OperationRequestArgs<"sofascore-team-tournaments">): Promise<OperationResponseMap["sofascore-team-tournaments"]>;
  teamTransfers(...args: OperationRequestArgs<"sofascore-team-transfers">): Promise<OperationResponseMap["sofascore-team-transfers"]>;
  tennisPlayerGrandSlamResults(...args: OperationRequestArgs<"sofascore-tennis-player-grand-slam-results">): Promise<OperationResponseMap["sofascore-tennis-player-grand-slam-results"]>;
  tournamentCuptree(...args: OperationRequestArgs<"sofascore-tournament-cuptree">): Promise<OperationResponseMap["sofascore-tournament-cuptree"]>;
  tournamentInfo(...args: OperationRequestArgs<"sofascore-tournament-info">): Promise<OperationResponseMap["sofascore-tournament-info"]>;
  tournamentPlayerOfTheSeason(...args: OperationRequestArgs<"sofascore-tournament-player-of-the-season">): Promise<OperationResponseMap["sofascore-tournament-player-of-the-season"]>;
  tournamentPlayerStatistics(...args: OperationRequestArgs<"sofascore-tournament-player-statistics">): Promise<OperationResponseMap["sofascore-tournament-player-statistics"]>;
  tournamentRounds(...args: OperationRequestArgs<"sofascore-tournament-rounds">): Promise<OperationResponseMap["sofascore-tournament-rounds"]>;
  tournamentSeasons(...args: OperationRequestArgs<"sofascore-tournament-seasons">): Promise<OperationResponseMap["sofascore-tournament-seasons"]>;
  tournamentStatisticsInfo(...args: OperationRequestArgs<"sofascore-tournament-statistics-info">): Promise<OperationResponseMap["sofascore-tournament-statistics-info"]>;
  tournamentTeamOfTheSeason(...args: OperationRequestArgs<"sofascore-tournament-team-of-the-season">): Promise<OperationResponseMap["sofascore-tournament-team-of-the-season"]>;
  tournamentTeams(...args: OperationRequestArgs<"sofascore-tournament-teams">): Promise<OperationResponseMap["sofascore-tournament-teams"]>;
  tournamentTopPlayers(...args: OperationRequestArgs<"sofascore-tournament-top-players">): Promise<OperationResponseMap["sofascore-tournament-top-players"]>;
  tournamentTopTeams(...args: OperationRequestArgs<"sofascore-tournament-top-teams">): Promise<OperationResponseMap["sofascore-tournament-top-teams"]>;
  tournamentVenues(...args: OperationRequestArgs<"sofascore-tournament-venues">): Promise<OperationResponseMap["sofascore-tournament-venues"]>;
  tournamentWinners(...args: OperationRequestArgs<"sofascore-tournament-winners">): Promise<OperationResponseMap["sofascore-tournament-winners"]>;
  tournamentsWithFeature(...args: OperationRequestArgs<"sofascore-tournaments-with-feature">): Promise<OperationResponseMap["sofascore-tournaments-with-feature"]>;
  trendingEvents(...args: OperationRequestArgs<"sofascore-trending-events">): Promise<OperationResponseMap["sofascore-trending-events"]>;
  trendingPlayers(...args: OperationRequestArgs<"sofascore-trending-players">): Promise<OperationResponseMap["sofascore-trending-players"]>;
  venue(...args: OperationRequestArgs<"sofascore-venue">): Promise<OperationResponseMap["sofascore-venue"]>;
  venueEvents(...args: OperationRequestArgs<"sofascore-venue-events">): Promise<OperationResponseMap["sofascore-venue-events"]>;
}
export { SofascoreClient as Client };
export const operations: Record<string, OperationDefinition>;
export const groups: Record<string, Record<string, string>>;
export const operationCount: number;
export const OperationIds: Readonly<Record<string, OperationId>>;
export const VERSION: string;
export * from "./types.js";
export default SofascoreClient;
