// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "sofascore-event": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event",
    "method": "GET",
    "path": "/sofascore/event",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-h2h": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-h2h",
    "method": "GET",
    "path": "/sofascore/event-h2h",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-incidents": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-incidents",
    "method": "GET",
    "path": "/sofascore/event-incidents",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-lineups": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-lineups",
    "method": "GET",
    "path": "/sofascore/event-lineups",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-odds": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-odds",
    "method": "GET",
    "path": "/sofascore/event-odds",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-statistics",
    "method": "GET",
    "path": "/sofascore/event-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-live-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-live-events",
    "method": "GET",
    "path": "/sofascore/live-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "football",
          "basketball",
          "tennis"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player",
    "method": "GET",
    "path": "/sofascore/player",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-round-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-round-events",
    "method": "GET",
    "path": "/sofascore/round-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "round",
        "required": true,
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-search",
    "method": "GET",
    "path": "/sofascore/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "q",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-standings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-standings",
    "method": "GET",
    "path": "/sofascore/standings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "total",
          "home",
          "away"
        ],
        "in": "query",
        "name": "type",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team",
    "method": "GET",
    "path": "/sofascore/team",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-events",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/team-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "next",
          "last"
        ],
        "in": "query",
        "name": "direction",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-players": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-players",
    "method": "GET",
    "path": "/sofascore/team-players",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-seasons",
    "method": "GET",
    "path": "/sofascore/tournament-seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "sofascore": {
    "event": "sofascore-event",
    "eventH2h": "sofascore-event-h2h",
    "eventIncidents": "sofascore-event-incidents",
    "eventLineups": "sofascore-event-lineups",
    "eventOdds": "sofascore-event-odds",
    "eventStatistics": "sofascore-event-statistics",
    "liveEvents": "sofascore-live-events",
    "player": "sofascore-player",
    "roundEvents": "sofascore-round-events",
    "search": "sofascore-search",
    "standings": "sofascore-standings",
    "team": "sofascore-team",
    "teamEvents": "sofascore-team-events",
    "teamPlayers": "sofascore-team-players",
    "tournamentSeasons": "sofascore-tournament-seasons"
  }
};

export const operationCount = 15;

export const OperationIds = Object.freeze({
  "SofascoreEvent": "sofascore-event",
  "SofascoreEventH2h": "sofascore-event-h2h",
  "SofascoreEventIncidents": "sofascore-event-incidents",
  "SofascoreEventLineups": "sofascore-event-lineups",
  "SofascoreEventOdds": "sofascore-event-odds",
  "SofascoreEventStatistics": "sofascore-event-statistics",
  "SofascoreLiveEvents": "sofascore-live-events",
  "SofascorePlayer": "sofascore-player",
  "SofascoreRoundEvents": "sofascore-round-events",
  "SofascoreSearch": "sofascore-search",
  "SofascoreStandings": "sofascore-standings",
  "SofascoreTeam": "sofascore-team",
  "SofascoreTeamEvents": "sofascore-team-events",
  "SofascoreTeamPlayers": "sofascore-team-players",
  "SofascoreTournamentSeasons": "sofascore-tournament-seasons"
});
