// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "sofascore-categories": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-categories",
    "method": "GET",
    "path": "/sofascore/categories",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "mma",
          "minifootball",
          "padel",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-category-tournaments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-category-tournaments",
    "method": "GET",
    "path": "/sofascore/category-tournaments",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event",
    "method": "GET",
    "path": "/sofascore/event",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-best-players": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-best-players",
    "method": "GET",
    "path": "/sofascore/event-best-players",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-comments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-comments",
    "method": "GET",
    "path": "/sofascore/event-comments",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-graph": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-graph",
    "method": "GET",
    "path": "/sofascore/event-graph",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-h2h": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-h2h",
    "method": "GET",
    "path": "/sofascore/event-h2h",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-incidents": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-incidents",
    "method": "GET",
    "path": "/sofascore/event-incidents",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-lineups": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-lineups",
    "method": "GET",
    "path": "/sofascore/event-lineups",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-odds": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-odds",
    "method": "GET",
    "path": "/sofascore/event-odds",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-player-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-player-statistics",
    "method": "GET",
    "path": "/sofascore/event-player-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "player_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-shotmap": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-shotmap",
    "method": "GET",
    "path": "/sofascore/event-shotmap",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-statistics",
    "method": "GET",
    "path": "/sofascore/event-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-live-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-live-events",
    "method": "GET",
    "path": "/sofascore/live-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "mma",
          "minifootball",
          "padel",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-manager": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-manager",
    "method": "GET",
    "path": "/sofascore/manager",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-manager-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-manager-events",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/manager-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player",
    "method": "GET",
    "path": "/sofascore/player",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-season-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-season-statistics",
    "method": "GET",
    "path": "/sofascore/player-season-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "tournament_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "home",
          "away",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-statistics-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-statistics-seasons",
    "method": "GET",
    "path": "/sofascore/player-statistics-seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-transfers": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-transfers",
    "method": "GET",
    "path": "/sofascore/player-transfers",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-ranking-types": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-ranking-types",
    "method": "GET",
    "path": "/sofascore/ranking-types",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-rankings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-rankings",
    "method": "GET",
    "path": "/sofascore/rankings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "34",
          "35",
          "36",
          "37",
          "40",
          "41",
          "42",
          "43",
          "44",
          "45",
          "46"
        ],
        "in": "query",
        "name": "type",
        "required": true,
        "type": "integer"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-round-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-round-events",
    "method": "GET",
    "path": "/sofascore/round-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "round",
        "required": true,
        "type": "integer"
      },
      {
        "in": "query",
        "name": "slug",
        "type": "string"
      },
      {
        "in": "query",
        "name": "prefix",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-scheduled-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-scheduled-events",
    "method": "GET",
    "path": "/sofascore/scheduled-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "category_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "date",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-scheduled-tournaments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-scheduled-tournaments",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/scheduled-tournaments",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "mma",
          "minifootball",
          "padel",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "date",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-search",
    "method": "GET",
    "path": "/sofascore/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "q",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-season-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-season-events",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/season-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "next",
          "last"
        ],
        "in": "query",
        "name": "direction",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-sports": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-sports",
    "method": "GET",
    "path": "/sofascore/sports",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-standings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-standings",
    "method": "GET",
    "path": "/sofascore/standings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "total",
          "home",
          "away"
        ],
        "in": "query",
        "name": "type",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team",
    "method": "GET",
    "path": "/sofascore/team",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-events",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/team-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "next",
          "last"
        ],
        "in": "query",
        "name": "direction",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-of-the-week": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-of-the-week",
    "method": "GET",
    "path": "/sofascore/team-of-the-week",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "period",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-of-the-week-periods": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-of-the-week-periods",
    "method": "GET",
    "path": "/sofascore/team-of-the-week-periods",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-players": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-players",
    "method": "GET",
    "path": "/sofascore/team-players",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-season-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-season-statistics",
    "method": "GET",
    "path": "/sofascore/team-season-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "tournament_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "home",
          "away",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-statistics-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-statistics-seasons",
    "method": "GET",
    "path": "/sofascore/team-statistics-seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-transfers": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-transfers",
    "method": "GET",
    "path": "/sofascore/team-transfers",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-info": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-info",
    "method": "GET",
    "path": "/sofascore/tournament-info",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-player-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-player-statistics",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/tournament-player-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "rating",
          "goals",
          "expectedGoals",
          "assists",
          "successfulDribbles",
          "tackles",
          "accuratePassesPercentage",
          "bigChancesMissed",
          "totalShots",
          "goalConversionPercentage",
          "interceptions",
          "clearances",
          "errorLeadToGoal",
          "outfielderBlocks",
          "bigChancesCreated",
          "accuratePasses",
          "keyPasses",
          "saves",
          "cleanSheet",
          "penaltySave",
          "savedShotsFromInsideTheBox",
          "runsOut"
        ],
        "in": "query",
        "name": "order",
        "type": "string"
      },
      {
        "enum": [
          "desc",
          "asc"
        ],
        "in": "query",
        "name": "direction",
        "type": "string"
      },
      {
        "enum": [
          "total",
          "perGame",
          "per90"
        ],
        "in": "query",
        "name": "accumulation",
        "type": "string"
      },
      {
        "enum": [
          "summary",
          "attack",
          "defence",
          "passing",
          "goalkeeper"
        ],
        "in": "query",
        "name": "group",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "offset",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-rounds": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-rounds",
    "method": "GET",
    "path": "/sofascore/tournament-rounds",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-seasons",
    "method": "GET",
    "path": "/sofascore/tournament-seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-top-players": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-top-players",
    "method": "GET",
    "path": "/sofascore/tournament-top-players",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-top-teams": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-top-teams",
    "method": "GET",
    "path": "/sofascore/tournament-top-teams",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "sofascore": {
    "categories": "sofascore-categories",
    "categoryTournaments": "sofascore-category-tournaments",
    "event": "sofascore-event",
    "eventBestPlayers": "sofascore-event-best-players",
    "eventComments": "sofascore-event-comments",
    "eventGraph": "sofascore-event-graph",
    "eventH2h": "sofascore-event-h2h",
    "eventIncidents": "sofascore-event-incidents",
    "eventLineups": "sofascore-event-lineups",
    "eventOdds": "sofascore-event-odds",
    "eventPlayerStatistics": "sofascore-event-player-statistics",
    "eventShotmap": "sofascore-event-shotmap",
    "eventStatistics": "sofascore-event-statistics",
    "liveEvents": "sofascore-live-events",
    "manager": "sofascore-manager",
    "managerEvents": "sofascore-manager-events",
    "player": "sofascore-player",
    "playerSeasonStatistics": "sofascore-player-season-statistics",
    "playerStatisticsSeasons": "sofascore-player-statistics-seasons",
    "playerTransfers": "sofascore-player-transfers",
    "rankingTypes": "sofascore-ranking-types",
    "rankings": "sofascore-rankings",
    "roundEvents": "sofascore-round-events",
    "scheduledEvents": "sofascore-scheduled-events",
    "scheduledTournaments": "sofascore-scheduled-tournaments",
    "search": "sofascore-search",
    "seasonEvents": "sofascore-season-events",
    "sports": "sofascore-sports",
    "standings": "sofascore-standings",
    "team": "sofascore-team",
    "teamEvents": "sofascore-team-events",
    "teamOfTheWeek": "sofascore-team-of-the-week",
    "teamOfTheWeekPeriods": "sofascore-team-of-the-week-periods",
    "teamPlayers": "sofascore-team-players",
    "teamSeasonStatistics": "sofascore-team-season-statistics",
    "teamStatisticsSeasons": "sofascore-team-statistics-seasons",
    "teamTransfers": "sofascore-team-transfers",
    "tournamentInfo": "sofascore-tournament-info",
    "tournamentPlayerStatistics": "sofascore-tournament-player-statistics",
    "tournamentRounds": "sofascore-tournament-rounds",
    "tournamentSeasons": "sofascore-tournament-seasons",
    "tournamentTopPlayers": "sofascore-tournament-top-players",
    "tournamentTopTeams": "sofascore-tournament-top-teams"
  }
};

export const operationCount = 43;

export const OperationIds = Object.freeze({
  "SofascoreCategories": "sofascore-categories",
  "SofascoreCategoryTournaments": "sofascore-category-tournaments",
  "SofascoreEvent": "sofascore-event",
  "SofascoreEventBestPlayers": "sofascore-event-best-players",
  "SofascoreEventComments": "sofascore-event-comments",
  "SofascoreEventGraph": "sofascore-event-graph",
  "SofascoreEventH2h": "sofascore-event-h2h",
  "SofascoreEventIncidents": "sofascore-event-incidents",
  "SofascoreEventLineups": "sofascore-event-lineups",
  "SofascoreEventOdds": "sofascore-event-odds",
  "SofascoreEventPlayerStatistics": "sofascore-event-player-statistics",
  "SofascoreEventShotmap": "sofascore-event-shotmap",
  "SofascoreEventStatistics": "sofascore-event-statistics",
  "SofascoreLiveEvents": "sofascore-live-events",
  "SofascoreManager": "sofascore-manager",
  "SofascoreManagerEvents": "sofascore-manager-events",
  "SofascorePlayer": "sofascore-player",
  "SofascorePlayerSeasonStatistics": "sofascore-player-season-statistics",
  "SofascorePlayerStatisticsSeasons": "sofascore-player-statistics-seasons",
  "SofascorePlayerTransfers": "sofascore-player-transfers",
  "SofascoreRankingTypes": "sofascore-ranking-types",
  "SofascoreRankings": "sofascore-rankings",
  "SofascoreRoundEvents": "sofascore-round-events",
  "SofascoreScheduledEvents": "sofascore-scheduled-events",
  "SofascoreScheduledTournaments": "sofascore-scheduled-tournaments",
  "SofascoreSearch": "sofascore-search",
  "SofascoreSeasonEvents": "sofascore-season-events",
  "SofascoreSports": "sofascore-sports",
  "SofascoreStandings": "sofascore-standings",
  "SofascoreTeam": "sofascore-team",
  "SofascoreTeamEvents": "sofascore-team-events",
  "SofascoreTeamOfTheWeek": "sofascore-team-of-the-week",
  "SofascoreTeamOfTheWeekPeriods": "sofascore-team-of-the-week-periods",
  "SofascoreTeamPlayers": "sofascore-team-players",
  "SofascoreTeamSeasonStatistics": "sofascore-team-season-statistics",
  "SofascoreTeamStatisticsSeasons": "sofascore-team-statistics-seasons",
  "SofascoreTeamTransfers": "sofascore-team-transfers",
  "SofascoreTournamentInfo": "sofascore-tournament-info",
  "SofascoreTournamentPlayerStatistics": "sofascore-tournament-player-statistics",
  "SofascoreTournamentRounds": "sofascore-tournament-rounds",
  "SofascoreTournamentSeasons": "sofascore-tournament-seasons",
  "SofascoreTournamentTopPlayers": "sofascore-tournament-top-players",
  "SofascoreTournamentTopTeams": "sofascore-tournament-top-teams"
});
