// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "sofascore-categories": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-categories",
    "method": "GET",
    "path": "/sofascore/categories",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "mma",
          "minifootball",
          "padel",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-category-tournaments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-category-tournaments",
    "method": "GET",
    "path": "/sofascore/category-tournaments",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-draft": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-draft",
    "method": "GET",
    "path": "/sofascore/draft",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "nba",
          "nfl"
        ],
        "in": "query",
        "name": "league",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-draft-picks": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-draft-picks",
    "method": "GET",
    "path": "/sofascore/draft-picks",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "nba",
          "nfl"
        ],
        "in": "query",
        "name": "league",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "year",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "round",
        "required": true,
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-esports-game": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-esports-game",
    "method": "GET",
    "path": "/sofascore/esports-game",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "statistics",
          "lineups",
          "bans",
          "rounds"
        ],
        "in": "query",
        "name": "part",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event",
    "method": "GET",
    "path": "/sofascore/event",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-at-bat-pitches": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-at-bat-pitches",
    "method": "GET",
    "path": "/sofascore/event-at-bat-pitches",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "at_bat_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-at-bats": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-at-bats",
    "method": "GET",
    "path": "/sofascore/event-at-bats",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-average-positions": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-average-positions",
    "method": "GET",
    "path": "/sofascore/event-average-positions",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-baseball-top-performers": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-baseball-top-performers",
    "method": "GET",
    "path": "/sofascore/event-baseball-top-performers",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-best-players": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-best-players",
    "method": "GET",
    "path": "/sofascore/event-best-players",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-comments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-comments",
    "method": "GET",
    "path": "/sofascore/event-comments",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-esports-games": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-esports-games",
    "method": "GET",
    "path": "/sofascore/event-esports-games",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-graph": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-graph",
    "method": "GET",
    "path": "/sofascore/event-graph",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-h2h": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-h2h",
    "method": "GET",
    "path": "/sofascore/event-h2h",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-highlights": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-highlights",
    "method": "GET",
    "path": "/sofascore/event-highlights",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-incidents": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-incidents",
    "method": "GET",
    "path": "/sofascore/event-incidents",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-innings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-innings",
    "method": "GET",
    "path": "/sofascore/event-innings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-lineups": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-lineups",
    "method": "GET",
    "path": "/sofascore/event-lineups",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-managers": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-managers",
    "method": "GET",
    "path": "/sofascore/event-managers",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-odds": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-odds",
    "method": "GET",
    "path": "/sofascore/event-odds",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-player-heatmap": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-player-heatmap",
    "method": "GET",
    "path": "/sofascore/event-player-heatmap",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "player_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-player-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-player-statistics",
    "method": "GET",
    "path": "/sofascore/event-player-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "player_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-point-by-point": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-point-by-point",
    "method": "GET",
    "path": "/sofascore/event-point-by-point",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-pregame-form": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-pregame-form",
    "method": "GET",
    "path": "/sofascore/event-pregame-form",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-shotmap": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-shotmap",
    "method": "GET",
    "path": "/sofascore/event-shotmap",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-statistics",
    "method": "GET",
    "path": "/sofascore/event-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-team-heatmap": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-team-heatmap",
    "method": "GET",
    "path": "/sofascore/event-team-heatmap",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "team_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-team-streaks": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-team-streaks",
    "method": "GET",
    "path": "/sofascore/event-team-streaks",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-tennis-power": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-tennis-power",
    "method": "GET",
    "path": "/sofascore/event-tennis-power",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-tv-channels": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-tv-channels",
    "method": "GET",
    "path": "/sofascore/event-tv-channels",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "country",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-event-votes": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-event-votes",
    "method": "GET",
    "path": "/sofascore/event-votes",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-live-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-live-events",
    "method": "GET",
    "path": "/sofascore/live-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "mma",
          "minifootball",
          "padel",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-manager": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-manager",
    "method": "GET",
    "path": "/sofascore/manager",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-manager-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-manager-events",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/manager-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-mma-card": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-mma-card",
    "method": "GET",
    "path": "/sofascore/mma-card",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "org_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "card_id",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "all",
          "maincard",
          "prelims",
          "earlyprelims"
        ],
        "in": "query",
        "name": "part",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-mma-schedule": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-mma-schedule",
    "method": "GET",
    "path": "/sofascore/mma-schedule",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "org_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "month",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-odds-dropping": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-odds-dropping",
    "method": "GET",
    "path": "/sofascore/odds-dropping",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "all",
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "mma",
          "minifootball",
          "padel",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-odds-winning": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-odds-winning",
    "method": "GET",
    "path": "/sofascore/odds-winning",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "all",
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "mma",
          "minifootball",
          "padel",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player",
    "method": "GET",
    "path": "/sofascore/player",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-attributes": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-attributes",
    "method": "GET",
    "path": "/sofascore/player-attributes",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-events",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/player-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-last-year-summary": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-last-year-summary",
    "method": "GET",
    "path": "/sofascore/player-last-year-summary",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-national-team-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-national-team-statistics",
    "method": "GET",
    "path": "/sofascore/player-national-team-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-penalty-history": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-penalty-history",
    "method": "GET",
    "path": "/sofascore/player-penalty-history",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-ratings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-ratings",
    "method": "GET",
    "path": "/sofascore/player-ratings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "tournament_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "home",
          "away",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-season-heatmap": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-season-heatmap",
    "method": "GET",
    "path": "/sofascore/player-season-heatmap",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "tournament_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-season-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-season-statistics",
    "method": "GET",
    "path": "/sofascore/player-season-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "tournament_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "home",
          "away",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-statistical-rankings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-statistical-rankings",
    "method": "GET",
    "path": "/sofascore/player-statistical-rankings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-statistics-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-statistics-seasons",
    "method": "GET",
    "path": "/sofascore/player-statistics-seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-tournaments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-tournaments",
    "method": "GET",
    "path": "/sofascore/player-tournaments",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-player-transfers": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-player-transfers",
    "method": "GET",
    "path": "/sofascore/player-transfers",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-ranking-types": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-ranking-types",
    "method": "GET",
    "path": "/sofascore/ranking-types",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-rankings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-rankings",
    "method": "GET",
    "path": "/sofascore/rankings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "34",
          "35",
          "36",
          "37",
          "40",
          "41",
          "42",
          "43",
          "44",
          "45",
          "46"
        ],
        "in": "query",
        "name": "type",
        "required": true,
        "type": "integer"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-referee": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-referee",
    "method": "GET",
    "path": "/sofascore/referee",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-referee-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-referee-events",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/referee-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-referee-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-referee-statistics",
    "method": "GET",
    "path": "/sofascore/referee-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-round-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-round-events",
    "method": "GET",
    "path": "/sofascore/round-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "round",
        "required": true,
        "type": "integer"
      },
      {
        "in": "query",
        "name": "slug",
        "type": "string"
      },
      {
        "in": "query",
        "name": "prefix",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-scheduled-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-scheduled-events",
    "method": "GET",
    "path": "/sofascore/scheduled-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "category_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "date",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-scheduled-tournaments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-scheduled-tournaments",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/scheduled-tournaments",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "mma",
          "minifootball",
          "padel",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "date",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-search",
    "method": "GET",
    "path": "/sofascore/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "q",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-search-typed": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-search-typed",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/search-typed",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "events",
          "teams",
          "players",
          "managers",
          "referees",
          "venues",
          "unique_tournaments"
        ],
        "in": "query",
        "name": "type",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "q",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      },
      {
        "enum": [
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "mma",
          "minifootball",
          "padel",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-season-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-season-events",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/season-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "next",
          "last"
        ],
        "in": "query",
        "name": "direction",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-sports": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-sports",
    "method": "GET",
    "path": "/sofascore/sports",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-stage": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-stage",
    "method": "GET",
    "path": "/sofascore/stage",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-stage-categories": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-stage-categories",
    "method": "GET",
    "path": "/sofascore/stage-categories",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "motorsport",
          "cycling"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-stage-driver-performance": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-stage-driver-performance",
    "method": "GET",
    "path": "/sofascore/stage-driver-performance",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-stage-featured": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-stage-featured",
    "method": "GET",
    "path": "/sofascore/stage-featured",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "motorsport",
          "cycling"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-stage-schedule": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-stage-schedule",
    "method": "GET",
    "path": "/sofascore/stage-schedule",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "motorsport",
          "cycling"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "date",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-stage-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-stage-seasons",
    "method": "GET",
    "path": "/sofascore/stage-seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-stage-standings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-stage-standings",
    "method": "GET",
    "path": "/sofascore/stage-standings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "competitor",
          "team"
        ],
        "in": "query",
        "name": "type",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-stage-substages": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-stage-substages",
    "method": "GET",
    "path": "/sofascore/stage-substages",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-standings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-standings",
    "method": "GET",
    "path": "/sofascore/standings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "total",
          "home",
          "away"
        ],
        "in": "query",
        "name": "type",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team",
    "method": "GET",
    "path": "/sofascore/team",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-achievements": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-achievements",
    "method": "GET",
    "path": "/sofascore/team-achievements",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-events",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/team-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "next",
          "last"
        ],
        "in": "query",
        "name": "direction",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-goal-distributions": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-goal-distributions",
    "method": "GET",
    "path": "/sofascore/team-goal-distributions",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "tournament_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-near-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-near-events",
    "method": "GET",
    "path": "/sofascore/team-near-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-of-the-week": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-of-the-week",
    "method": "GET",
    "path": "/sofascore/team-of-the-week",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "period",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-of-the-week-periods": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-of-the-week-periods",
    "method": "GET",
    "path": "/sofascore/team-of-the-week-periods",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-performance": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-performance",
    "method": "GET",
    "path": "/sofascore/team-performance",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-player-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-player-statistics",
    "method": "GET",
    "path": "/sofascore/team-player-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "tournament_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "home",
          "away",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-player-statistics-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-player-statistics-seasons",
    "method": "GET",
    "path": "/sofascore/team-player-statistics-seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-players": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-players",
    "method": "GET",
    "path": "/sofascore/team-players",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-rankings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-rankings",
    "method": "GET",
    "path": "/sofascore/team-rankings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-season-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-season-statistics",
    "method": "GET",
    "path": "/sofascore/team-season-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "tournament_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "home",
          "away",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-statistics-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-statistics-seasons",
    "method": "GET",
    "path": "/sofascore/team-statistics-seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-top-players": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-top-players",
    "method": "GET",
    "path": "/sofascore/team-top-players",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "tournament_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-tournaments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-tournaments",
    "method": "GET",
    "path": "/sofascore/team-tournaments",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "all",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-team-transfers": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-team-transfers",
    "method": "GET",
    "path": "/sofascore/team-transfers",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tennis-player-grand-slam-results": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tennis-player-grand-slam-results",
    "method": "GET",
    "path": "/sofascore/tennis-player-grand-slam-results",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-cuptree": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-cuptree",
    "method": "GET",
    "path": "/sofascore/tournament-cuptree",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-info": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-info",
    "method": "GET",
    "path": "/sofascore/tournament-info",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-player-of-the-season": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-player-of-the-season",
    "method": "GET",
    "path": "/sofascore/tournament-player-of-the-season",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-player-statistics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-player-statistics",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/tournament-player-statistics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "rating",
          "goals",
          "expectedGoals",
          "assists",
          "successfulDribbles",
          "tackles",
          "accuratePassesPercentage",
          "bigChancesMissed",
          "totalShots",
          "goalConversionPercentage",
          "interceptions",
          "clearances",
          "errorLeadToGoal",
          "outfielderBlocks",
          "bigChancesCreated",
          "accuratePasses",
          "keyPasses",
          "saves",
          "cleanSheet",
          "penaltySave",
          "savedShotsFromInsideTheBox",
          "runsOut"
        ],
        "in": "query",
        "name": "order",
        "type": "string"
      },
      {
        "enum": [
          "desc",
          "asc"
        ],
        "in": "query",
        "name": "direction",
        "type": "string"
      },
      {
        "enum": [
          "total",
          "perGame",
          "per90"
        ],
        "in": "query",
        "name": "accumulation",
        "type": "string"
      },
      {
        "enum": [
          "summary",
          "attack",
          "defence",
          "passing",
          "goalkeeper"
        ],
        "in": "query",
        "name": "group",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "offset",
        "type": "integer"
      },
      {
        "collectionFormat": "csv",
        "in": "query",
        "name": "team",
        "type": "array"
      },
      {
        "collectionFormat": "csv",
        "in": "query",
        "name": "nationality",
        "type": "array"
      },
      {
        "collectionFormat": "csv",
        "enum": [
          "G",
          "D",
          "M",
          "F"
        ],
        "in": "query",
        "name": "position",
        "type": "array"
      },
      {
        "in": "query",
        "name": "min_appearances",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "min_minutes",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-rounds": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-rounds",
    "method": "GET",
    "path": "/sofascore/tournament-rounds",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-seasons",
    "method": "GET",
    "path": "/sofascore/tournament-seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-statistics-info": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-statistics-info",
    "method": "GET",
    "path": "/sofascore/tournament-statistics-info",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-team-of-the-season": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-team-of-the-season",
    "method": "GET",
    "path": "/sofascore/tournament-team-of-the-season",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-teams": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-teams",
    "method": "GET",
    "path": "/sofascore/tournament-teams",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-top-players": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-top-players",
    "method": "GET",
    "path": "/sofascore/tournament-top-players",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-top-teams": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-top-teams",
    "method": "GET",
    "path": "/sofascore/tournament-top-teams",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "regular_season",
          "playoffs"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-venues": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-venues",
    "method": "GET",
    "path": "/sofascore/tournament-venues",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournament-winners": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournament-winners",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/tournament-winners",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-tournaments-with-feature": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-tournaments-with-feature",
    "method": "GET",
    "path": "/sofascore/tournaments-with-feature",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "cuptree",
          "standings",
          "totw",
          "power_rankings"
        ],
        "in": "query",
        "name": "feature",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "minifootball",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-trending-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-trending-events",
    "method": "GET",
    "path": "/sofascore/trending-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "country",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-trending-players": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-trending-players",
    "method": "GET",
    "path": "/sofascore/trending-players",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "football",
          "basketball"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-venue": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-venue",
    "method": "GET",
    "path": "/sofascore/venue",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "sofascore-venue-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "sofascore-venue-events",
    "method": "GET",
    "paginatable": true,
    "path": "/sofascore/venue-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "next",
          "last"
        ],
        "in": "query",
        "name": "direction",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "all",
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "baseball",
          "basketball",
          "beach-volley",
          "cricket",
          "darts",
          "esports",
          "floorball",
          "football",
          "futsal",
          "handball",
          "ice-hockey",
          "mma",
          "minifootball",
          "padel",
          "rugby",
          "snooker",
          "table-tennis",
          "tennis",
          "volleyball",
          "waterpolo"
        ],
        "in": "query",
        "name": "sport",
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "tournament",
        "type": "string"
      },
      {
        "in": "query",
        "name": "season",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "sofascore": {
    "categories": "sofascore-categories",
    "categoryTournaments": "sofascore-category-tournaments",
    "draft": "sofascore-draft",
    "draftPicks": "sofascore-draft-picks",
    "esportsGame": "sofascore-esports-game",
    "event": "sofascore-event",
    "eventAtBatPitches": "sofascore-event-at-bat-pitches",
    "eventAtBats": "sofascore-event-at-bats",
    "eventAveragePositions": "sofascore-event-average-positions",
    "eventBaseballTopPerformers": "sofascore-event-baseball-top-performers",
    "eventBestPlayers": "sofascore-event-best-players",
    "eventComments": "sofascore-event-comments",
    "eventEsportsGames": "sofascore-event-esports-games",
    "eventGraph": "sofascore-event-graph",
    "eventH2h": "sofascore-event-h2h",
    "eventHighlights": "sofascore-event-highlights",
    "eventIncidents": "sofascore-event-incidents",
    "eventInnings": "sofascore-event-innings",
    "eventLineups": "sofascore-event-lineups",
    "eventManagers": "sofascore-event-managers",
    "eventOdds": "sofascore-event-odds",
    "eventPlayerHeatmap": "sofascore-event-player-heatmap",
    "eventPlayerStatistics": "sofascore-event-player-statistics",
    "eventPointByPoint": "sofascore-event-point-by-point",
    "eventPregameForm": "sofascore-event-pregame-form",
    "eventShotmap": "sofascore-event-shotmap",
    "eventStatistics": "sofascore-event-statistics",
    "eventTeamHeatmap": "sofascore-event-team-heatmap",
    "eventTeamStreaks": "sofascore-event-team-streaks",
    "eventTennisPower": "sofascore-event-tennis-power",
    "eventTvChannels": "sofascore-event-tv-channels",
    "eventVotes": "sofascore-event-votes",
    "liveEvents": "sofascore-live-events",
    "manager": "sofascore-manager",
    "managerEvents": "sofascore-manager-events",
    "mmaCard": "sofascore-mma-card",
    "mmaSchedule": "sofascore-mma-schedule",
    "oddsDropping": "sofascore-odds-dropping",
    "oddsWinning": "sofascore-odds-winning",
    "player": "sofascore-player",
    "playerAttributes": "sofascore-player-attributes",
    "playerEvents": "sofascore-player-events",
    "playerLastYearSummary": "sofascore-player-last-year-summary",
    "playerNationalTeamStatistics": "sofascore-player-national-team-statistics",
    "playerPenaltyHistory": "sofascore-player-penalty-history",
    "playerRatings": "sofascore-player-ratings",
    "playerSeasonHeatmap": "sofascore-player-season-heatmap",
    "playerSeasonStatistics": "sofascore-player-season-statistics",
    "playerStatisticalRankings": "sofascore-player-statistical-rankings",
    "playerStatisticsSeasons": "sofascore-player-statistics-seasons",
    "playerTournaments": "sofascore-player-tournaments",
    "playerTransfers": "sofascore-player-transfers",
    "rankingTypes": "sofascore-ranking-types",
    "rankings": "sofascore-rankings",
    "referee": "sofascore-referee",
    "refereeEvents": "sofascore-referee-events",
    "refereeStatistics": "sofascore-referee-statistics",
    "roundEvents": "sofascore-round-events",
    "scheduledEvents": "sofascore-scheduled-events",
    "scheduledTournaments": "sofascore-scheduled-tournaments",
    "search": "sofascore-search",
    "searchTyped": "sofascore-search-typed",
    "seasonEvents": "sofascore-season-events",
    "sports": "sofascore-sports",
    "stage": "sofascore-stage",
    "stageCategories": "sofascore-stage-categories",
    "stageDriverPerformance": "sofascore-stage-driver-performance",
    "stageFeatured": "sofascore-stage-featured",
    "stageSchedule": "sofascore-stage-schedule",
    "stageSeasons": "sofascore-stage-seasons",
    "stageStandings": "sofascore-stage-standings",
    "stageSubstages": "sofascore-stage-substages",
    "standings": "sofascore-standings",
    "team": "sofascore-team",
    "teamAchievements": "sofascore-team-achievements",
    "teamEvents": "sofascore-team-events",
    "teamGoalDistributions": "sofascore-team-goal-distributions",
    "teamNearEvents": "sofascore-team-near-events",
    "teamOfTheWeek": "sofascore-team-of-the-week",
    "teamOfTheWeekPeriods": "sofascore-team-of-the-week-periods",
    "teamPerformance": "sofascore-team-performance",
    "teamPlayerStatistics": "sofascore-team-player-statistics",
    "teamPlayerStatisticsSeasons": "sofascore-team-player-statistics-seasons",
    "teamPlayers": "sofascore-team-players",
    "teamRankings": "sofascore-team-rankings",
    "teamSeasonStatistics": "sofascore-team-season-statistics",
    "teamStatisticsSeasons": "sofascore-team-statistics-seasons",
    "teamTopPlayers": "sofascore-team-top-players",
    "teamTournaments": "sofascore-team-tournaments",
    "teamTransfers": "sofascore-team-transfers",
    "tennisPlayerGrandSlamResults": "sofascore-tennis-player-grand-slam-results",
    "tournamentCuptree": "sofascore-tournament-cuptree",
    "tournamentInfo": "sofascore-tournament-info",
    "tournamentPlayerOfTheSeason": "sofascore-tournament-player-of-the-season",
    "tournamentPlayerStatistics": "sofascore-tournament-player-statistics",
    "tournamentRounds": "sofascore-tournament-rounds",
    "tournamentSeasons": "sofascore-tournament-seasons",
    "tournamentStatisticsInfo": "sofascore-tournament-statistics-info",
    "tournamentTeamOfTheSeason": "sofascore-tournament-team-of-the-season",
    "tournamentTeams": "sofascore-tournament-teams",
    "tournamentTopPlayers": "sofascore-tournament-top-players",
    "tournamentTopTeams": "sofascore-tournament-top-teams",
    "tournamentVenues": "sofascore-tournament-venues",
    "tournamentWinners": "sofascore-tournament-winners",
    "tournamentsWithFeature": "sofascore-tournaments-with-feature",
    "trendingEvents": "sofascore-trending-events",
    "trendingPlayers": "sofascore-trending-players",
    "venue": "sofascore-venue",
    "venueEvents": "sofascore-venue-events"
  }
};

export const operationCount = 109;

export const OperationIds = Object.freeze({
  "SofascoreCategories": "sofascore-categories",
  "SofascoreCategoryTournaments": "sofascore-category-tournaments",
  "SofascoreDraft": "sofascore-draft",
  "SofascoreDraftPicks": "sofascore-draft-picks",
  "SofascoreEsportsGame": "sofascore-esports-game",
  "SofascoreEvent": "sofascore-event",
  "SofascoreEventAtBatPitches": "sofascore-event-at-bat-pitches",
  "SofascoreEventAtBats": "sofascore-event-at-bats",
  "SofascoreEventAveragePositions": "sofascore-event-average-positions",
  "SofascoreEventBaseballTopPerformers": "sofascore-event-baseball-top-performers",
  "SofascoreEventBestPlayers": "sofascore-event-best-players",
  "SofascoreEventComments": "sofascore-event-comments",
  "SofascoreEventEsportsGames": "sofascore-event-esports-games",
  "SofascoreEventGraph": "sofascore-event-graph",
  "SofascoreEventH2h": "sofascore-event-h2h",
  "SofascoreEventHighlights": "sofascore-event-highlights",
  "SofascoreEventIncidents": "sofascore-event-incidents",
  "SofascoreEventInnings": "sofascore-event-innings",
  "SofascoreEventLineups": "sofascore-event-lineups",
  "SofascoreEventManagers": "sofascore-event-managers",
  "SofascoreEventOdds": "sofascore-event-odds",
  "SofascoreEventPlayerHeatmap": "sofascore-event-player-heatmap",
  "SofascoreEventPlayerStatistics": "sofascore-event-player-statistics",
  "SofascoreEventPointByPoint": "sofascore-event-point-by-point",
  "SofascoreEventPregameForm": "sofascore-event-pregame-form",
  "SofascoreEventShotmap": "sofascore-event-shotmap",
  "SofascoreEventStatistics": "sofascore-event-statistics",
  "SofascoreEventTeamHeatmap": "sofascore-event-team-heatmap",
  "SofascoreEventTeamStreaks": "sofascore-event-team-streaks",
  "SofascoreEventTennisPower": "sofascore-event-tennis-power",
  "SofascoreEventTvChannels": "sofascore-event-tv-channels",
  "SofascoreEventVotes": "sofascore-event-votes",
  "SofascoreLiveEvents": "sofascore-live-events",
  "SofascoreManager": "sofascore-manager",
  "SofascoreManagerEvents": "sofascore-manager-events",
  "SofascoreMmaCard": "sofascore-mma-card",
  "SofascoreMmaSchedule": "sofascore-mma-schedule",
  "SofascoreOddsDropping": "sofascore-odds-dropping",
  "SofascoreOddsWinning": "sofascore-odds-winning",
  "SofascorePlayer": "sofascore-player",
  "SofascorePlayerAttributes": "sofascore-player-attributes",
  "SofascorePlayerEvents": "sofascore-player-events",
  "SofascorePlayerLastYearSummary": "sofascore-player-last-year-summary",
  "SofascorePlayerNationalTeamStatistics": "sofascore-player-national-team-statistics",
  "SofascorePlayerPenaltyHistory": "sofascore-player-penalty-history",
  "SofascorePlayerRatings": "sofascore-player-ratings",
  "SofascorePlayerSeasonHeatmap": "sofascore-player-season-heatmap",
  "SofascorePlayerSeasonStatistics": "sofascore-player-season-statistics",
  "SofascorePlayerStatisticalRankings": "sofascore-player-statistical-rankings",
  "SofascorePlayerStatisticsSeasons": "sofascore-player-statistics-seasons",
  "SofascorePlayerTournaments": "sofascore-player-tournaments",
  "SofascorePlayerTransfers": "sofascore-player-transfers",
  "SofascoreRankingTypes": "sofascore-ranking-types",
  "SofascoreRankings": "sofascore-rankings",
  "SofascoreReferee": "sofascore-referee",
  "SofascoreRefereeEvents": "sofascore-referee-events",
  "SofascoreRefereeStatistics": "sofascore-referee-statistics",
  "SofascoreRoundEvents": "sofascore-round-events",
  "SofascoreScheduledEvents": "sofascore-scheduled-events",
  "SofascoreScheduledTournaments": "sofascore-scheduled-tournaments",
  "SofascoreSearch": "sofascore-search",
  "SofascoreSearchTyped": "sofascore-search-typed",
  "SofascoreSeasonEvents": "sofascore-season-events",
  "SofascoreSports": "sofascore-sports",
  "SofascoreStage": "sofascore-stage",
  "SofascoreStageCategories": "sofascore-stage-categories",
  "SofascoreStageDriverPerformance": "sofascore-stage-driver-performance",
  "SofascoreStageFeatured": "sofascore-stage-featured",
  "SofascoreStageSchedule": "sofascore-stage-schedule",
  "SofascoreStageSeasons": "sofascore-stage-seasons",
  "SofascoreStageStandings": "sofascore-stage-standings",
  "SofascoreStageSubstages": "sofascore-stage-substages",
  "SofascoreStandings": "sofascore-standings",
  "SofascoreTeam": "sofascore-team",
  "SofascoreTeamAchievements": "sofascore-team-achievements",
  "SofascoreTeamEvents": "sofascore-team-events",
  "SofascoreTeamGoalDistributions": "sofascore-team-goal-distributions",
  "SofascoreTeamNearEvents": "sofascore-team-near-events",
  "SofascoreTeamOfTheWeek": "sofascore-team-of-the-week",
  "SofascoreTeamOfTheWeekPeriods": "sofascore-team-of-the-week-periods",
  "SofascoreTeamPerformance": "sofascore-team-performance",
  "SofascoreTeamPlayerStatistics": "sofascore-team-player-statistics",
  "SofascoreTeamPlayerStatisticsSeasons": "sofascore-team-player-statistics-seasons",
  "SofascoreTeamPlayers": "sofascore-team-players",
  "SofascoreTeamRankings": "sofascore-team-rankings",
  "SofascoreTeamSeasonStatistics": "sofascore-team-season-statistics",
  "SofascoreTeamStatisticsSeasons": "sofascore-team-statistics-seasons",
  "SofascoreTeamTopPlayers": "sofascore-team-top-players",
  "SofascoreTeamTournaments": "sofascore-team-tournaments",
  "SofascoreTeamTransfers": "sofascore-team-transfers",
  "SofascoreTennisPlayerGrandSlamResults": "sofascore-tennis-player-grand-slam-results",
  "SofascoreTournamentCuptree": "sofascore-tournament-cuptree",
  "SofascoreTournamentInfo": "sofascore-tournament-info",
  "SofascoreTournamentPlayerOfTheSeason": "sofascore-tournament-player-of-the-season",
  "SofascoreTournamentPlayerStatistics": "sofascore-tournament-player-statistics",
  "SofascoreTournamentRounds": "sofascore-tournament-rounds",
  "SofascoreTournamentSeasons": "sofascore-tournament-seasons",
  "SofascoreTournamentStatisticsInfo": "sofascore-tournament-statistics-info",
  "SofascoreTournamentTeamOfTheSeason": "sofascore-tournament-team-of-the-season",
  "SofascoreTournamentTeams": "sofascore-tournament-teams",
  "SofascoreTournamentTopPlayers": "sofascore-tournament-top-players",
  "SofascoreTournamentTopTeams": "sofascore-tournament-top-teams",
  "SofascoreTournamentVenues": "sofascore-tournament-venues",
  "SofascoreTournamentWinners": "sofascore-tournament-winners",
  "SofascoreTournamentsWithFeature": "sofascore-tournaments-with-feature",
  "SofascoreTrendingEvents": "sofascore-trending-events",
  "SofascoreTrendingPlayers": "sofascore-trending-players",
  "SofascoreVenue": "sofascore-venue",
  "SofascoreVenueEvents": "sofascore-venue-events"
});
