// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelSofascoreTournamentSeasonsResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreTournamentSeasonsResponse;
  "msg"?: string;
}

export interface ModelSofascoreTournamentSeasonsResponse {
  "count"?: number;
  "fetched_at"?: string;
  "seasons"?: Array<ModelSofascoreSeason>;
  "source_url"?: string;
  "tournament_id"?: number;
}

export interface ModelSofascoreSeason {
  "id"?: number;
  "name"?: string;
  "year"?: string;
}

export interface ModelSofascoreTeamPlayersResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreTeamPlayersResponse;
  "msg"?: string;
}

export interface ModelSofascoreTeamPlayersResponse {
  "count"?: number;
  "fetched_at"?: string;
  "players"?: Array<ModelSofascoreSquadPlayer>;
  "source_url"?: string;
  "team_id"?: number;
}

export interface ModelSofascoreSquadPlayer {
  "country"?: string;
  "date_of_birth"?: string;
  "height"?: number;
  "id"?: number;
  "jersey_number"?: string;
  "market_value"?: number;
  "market_value_currency"?: string;
  "name"?: string;
  "position"?: string;
  "preferred_foot"?: string;
  "short_name"?: string;
  "slug"?: string;
}

export interface ModelSofascoreTeamEventsResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreTeamEventsResponse;
  "msg"?: string;
}

export interface ModelSofascoreTeamEventsResponse {
  "count"?: number;
  "direction"?: string;
  "events"?: Array<ModelSofascoreEventSummary>;
  "fetched_at"?: string;
  "has_next_page"?: boolean;
  "page"?: number;
  "source_url"?: string;
  "team_id"?: number;
}

export interface ModelSofascoreEventSummary {
  "away_score"?: ModelSofascoreScoreLine;
  "away_team"?: ModelSofascoreTeamRef;
  "home_score"?: ModelSofascoreScoreLine;
  "home_team"?: ModelSofascoreTeamRef;
  "id"?: number;
  "slug"?: string;
  "start_time"?: string;
  "start_timestamp"?: number;
  "status"?: ModelSofascoreEventStatus;
  "tournament"?: ModelSofascoreTournamentRef;
  "winner_code"?: number;
}

export interface ModelSofascoreTournamentRef {
  "category"?: string;
  "id"?: number;
  "name"?: string;
  "slug"?: string;
  "unique_tournament_id"?: number;
  "unique_tournament_name"?: string;
}

export interface ModelSofascoreEventStatus {
  "code"?: number;
  "description"?: string;
  "type"?: string;
}

export interface ModelSofascoreTeamRef {
  "country"?: string;
  "id"?: number;
  "name"?: string;
  "national"?: boolean;
  "short_name"?: string;
  "slug"?: string;
}

export interface ModelSofascoreScoreLine {
  "current"?: number;
  "period1"?: number;
  "period2"?: number;
}

export interface ModelSofascoreTeamResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreTeamResponse;
  "msg"?: string;
}

export interface ModelSofascoreTeamResponse {
  "fetched_at"?: string;
  "source_url"?: string;
  "team"?: ModelSofascoreTeamDetail;
}

export interface ModelSofascoreTeamDetail {
  "country"?: string;
  "id"?: number;
  "manager"?: string;
  "name"?: string;
  "national"?: boolean;
  "primary_color"?: string;
  "short_name"?: string;
  "slug"?: string;
  "sport"?: string;
  "tournament_id"?: number;
  "tournament_name"?: string;
  "venue"?: string;
  "venue_capacity"?: number;
  "venue_city"?: string;
}

export interface ModelSofascoreStandingsResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreStandingsResponse;
  "msg"?: string;
}

export interface ModelSofascoreStandingsResponse {
  "fetched_at"?: string;
  "groups"?: Array<ModelSofascoreStandingsGroup>;
  "season_id"?: number;
  "source_url"?: string;
  "tournament_id"?: number;
  "type"?: string;
}

export interface ModelSofascoreStandingsGroup {
  "name"?: string;
  "rows"?: Array<ModelSofascoreStandingsRow>;
}

export interface ModelSofascoreStandingsRow {
  "draws"?: number;
  "losses"?: number;
  "matches"?: number;
  "points"?: number;
  "position"?: number;
  "promotion"?: string;
  "scores_against"?: number;
  "scores_for"?: number;
  "team"?: ModelSofascoreTeamRef;
  "wins"?: number;
}

export interface ModelSofascoreSearchResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreSearchResponse;
  "msg"?: string;
}

export interface ModelSofascoreSearchResponse {
  "count"?: number;
  "fetched_at"?: string;
  "query"?: string;
  "results"?: Array<ModelSofascoreSearchResult>;
  "source_url"?: string;
}

export interface ModelSofascoreSearchResult {
  "country"?: string;
  "id"?: number;
  "name"?: string;
  "slug"?: string;
  "sport"?: string;
  "team_id"?: number;
  "team_name"?: string;
  "type"?: string;
}

export interface ModelSofascoreRoundEventsResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreRoundEventsResponse;
  "msg"?: string;
}

export interface ModelSofascoreRoundEventsResponse {
  "count"?: number;
  "events"?: Array<ModelSofascoreEventSummary>;
  "fetched_at"?: string;
  "has_next_page"?: boolean;
  "round"?: number;
  "season_id"?: number;
  "source_url"?: string;
  "tournament_id"?: number;
}

export interface ModelSofascorePlayerResponseDoc {
  "code"?: number;
  "data"?: ModelSofascorePlayerResponse;
  "msg"?: string;
}

export interface ModelSofascorePlayerResponse {
  "fetched_at"?: string;
  "player"?: ModelSofascorePlayerDetail;
  "source_url"?: string;
}

export interface ModelSofascorePlayerDetail {
  "country"?: string;
  "date_of_birth"?: string;
  "deceased"?: boolean;
  "height"?: number;
  "id"?: number;
  "jersey_number"?: string;
  "market_value"?: number;
  "market_value_currency"?: string;
  "name"?: string;
  "position"?: string;
  "preferred_foot"?: string;
  "short_name"?: string;
  "slug"?: string;
  "team"?: ModelSofascoreTeamRef;
}

export interface ModelSofascoreLiveEventsResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreLiveEventsResponse;
  "msg"?: string;
}

export interface ModelSofascoreLiveEventsResponse {
  "count"?: number;
  "events"?: Array<ModelSofascoreEventSummary>;
  "fetched_at"?: string;
  "source_url"?: string;
  "sport"?: string;
}

export interface ModelSofascoreEventStatisticsResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreEventStatisticsResponse;
  "msg"?: string;
}

export interface ModelSofascoreEventStatisticsResponse {
  "event_id"?: number;
  "fetched_at"?: string;
  "periods"?: Array<ModelSofascoreStatPeriod>;
  "source_url"?: string;
}

export interface ModelSofascoreStatPeriod {
  "groups"?: Array<ModelSofascoreStatGroup>;
  "period"?: string;
}

export interface ModelSofascoreStatGroup {
  "items"?: Array<ModelSofascoreStatItem>;
  "name"?: string;
}

export interface ModelSofascoreStatItem {
  "away"?: string;
  "home"?: string;
  "key"?: string;
  "name"?: string;
}

export interface ModelSofascoreEventOddsResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreEventOddsResponse;
  "msg"?: string;
}

export interface ModelSofascoreEventOddsResponse {
  "count"?: number;
  "event_id"?: number;
  "fetched_at"?: string;
  "markets"?: Array<ModelSofascoreOddsMarket>;
  "source_url"?: string;
}

export interface ModelSofascoreOddsMarket {
  "choices"?: Array<ModelSofascoreOddsChoice>;
  "group"?: string;
  "name"?: string;
  "period"?: string;
  "suspended"?: boolean;
}

export interface ModelSofascoreOddsChoice {
  "name"?: string;
  "value"?: string;
  "winning"?: boolean;
}

export interface ModelSofascoreEventLineupsResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreEventLineupsResponse;
  "msg"?: string;
}

export interface ModelSofascoreEventLineupsResponse {
  "away"?: ModelSofascoreTeamLineup;
  "confirmed"?: boolean;
  "event_id"?: number;
  "fetched_at"?: string;
  "home"?: ModelSofascoreTeamLineup;
  "source_url"?: string;
}

export interface ModelSofascoreTeamLineup {
  "formation"?: string;
  "players"?: Array<ModelSofascoreLineupPlayer>;
}

export interface ModelSofascoreLineupPlayer {
  "jersey_number"?: string;
  "player"?: ModelSofascorePlayerRef;
  "position"?: string;
  "substitute"?: boolean;
}

export interface ModelSofascorePlayerRef {
  "country"?: string;
  "id"?: number;
  "name"?: string;
  "position"?: string;
  "short_name"?: string;
  "slug"?: string;
}

export interface ModelSofascoreEventIncidentsResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreEventIncidentsResponse;
  "msg"?: string;
}

export interface ModelSofascoreEventIncidentsResponse {
  "count"?: number;
  "event_id"?: number;
  "fetched_at"?: string;
  "incidents"?: Array<ModelSofascoreIncident>;
  "source_url"?: string;
}

export interface ModelSofascoreIncident {
  "added_time"?: number;
  "away_score"?: number;
  "card_color"?: string;
  "home_score"?: number;
  "is_home"?: boolean;
  "player"?: string;
  "player_in"?: string;
  "player_out"?: string;
  "reason"?: string;
  "text"?: string;
  "time"?: number;
  "type"?: string;
}

export interface ModelSofascoreEventH2HresponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreEventH2Hresponse;
  "msg"?: string;
}

export interface ModelSofascoreEventH2Hresponse {
  "event_id"?: number;
  "fetched_at"?: string;
  "manager_duel"?: ModelSofascoreTeamDuel;
  "source_url"?: string;
  "team_duel"?: ModelSofascoreTeamDuel;
}

export interface ModelSofascoreTeamDuel {
  "away_wins"?: number;
  "draws"?: number;
  "home_wins"?: number;
}

export interface ModelSofascoreEventResponseDoc {
  "code"?: number;
  "data"?: ModelSofascoreEventResponse;
  "msg"?: string;
}

export interface ModelSofascoreEventResponse {
  "event"?: ModelSofascoreEventDetail;
  "fetched_at"?: string;
  "source_url"?: string;
}

export interface ModelSofascoreEventDetail {
  "attendance"?: number;
  "away_score"?: ModelSofascoreScoreLine;
  "away_team"?: ModelSofascoreTeamRef;
  "home_score"?: ModelSofascoreScoreLine;
  "home_team"?: ModelSofascoreTeamRef;
  "id"?: number;
  "referee"?: ModelSofascoreReferee;
  "slug"?: string;
  "start_time"?: string;
  "start_timestamp"?: number;
  "status"?: ModelSofascoreEventStatus;
  "tournament"?: ModelSofascoreTournamentRef;
  "venue"?: ModelSofascoreVenue;
  "winner_code"?: number;
}

export interface ModelSofascoreVenue {
  "capacity"?: number;
  "city"?: string;
  "country"?: string;
  "name"?: string;
}

export interface ModelSofascoreReferee {
  "country"?: string;
  "id"?: number;
  "name"?: string;
}

export type SofascoreEventResponse = CrawloraResponse<ModelSofascoreEventResponseDoc>;
export interface SofascoreEventParams {
  "id": string;
}

export type SofascoreEventH2hResponse = CrawloraResponse<ModelSofascoreEventH2HresponseDoc>;
export interface SofascoreEventH2hParams {
  "id": string;
}

export type SofascoreEventIncidentsResponse = CrawloraResponse<ModelSofascoreEventIncidentsResponseDoc>;
export interface SofascoreEventIncidentsParams {
  "id": string;
}

export type SofascoreEventLineupsResponse = CrawloraResponse<ModelSofascoreEventLineupsResponseDoc>;
export interface SofascoreEventLineupsParams {
  "id": string;
}

export type SofascoreEventOddsResponse = CrawloraResponse<ModelSofascoreEventOddsResponseDoc>;
export interface SofascoreEventOddsParams {
  "id": string;
}

export type SofascoreEventStatisticsResponse = CrawloraResponse<ModelSofascoreEventStatisticsResponseDoc>;
export interface SofascoreEventStatisticsParams {
  "id": string;
}

export type SofascoreLiveEventsResponse = CrawloraResponse<ModelSofascoreLiveEventsResponseDoc>;
export interface SofascoreLiveEventsParams {
  "sport": "football" | "basketball" | "tennis";
}

export type SofascorePlayerResponse = CrawloraResponse<ModelSofascorePlayerResponseDoc>;
export interface SofascorePlayerParams {
  "id": string;
}

export type SofascoreRoundEventsResponse = CrawloraResponse<ModelSofascoreRoundEventsResponseDoc>;
export interface SofascoreRoundEventsParams {
  "id": string;
  "season": string;
  "round": number;
}

export type SofascoreSearchResponse = CrawloraResponse<ModelSofascoreSearchResponseDoc>;
export interface SofascoreSearchParams {
  "q": string;
}

export type SofascoreStandingsResponse = CrawloraResponse<ModelSofascoreStandingsResponseDoc>;
export interface SofascoreStandingsParams {
  "id": string;
  "season": string;
  "type": "total" | "home" | "away";
}

export type SofascoreTeamResponse = CrawloraResponse<ModelSofascoreTeamResponseDoc>;
export interface SofascoreTeamParams {
  "id": string;
}

export type SofascoreTeamEventsResponse = CrawloraResponse<ModelSofascoreTeamEventsResponseDoc>;
export interface SofascoreTeamEventsParams {
  "id": string;
  "direction": "next" | "last";
  "page"?: number;
}

export type SofascoreTeamPlayersResponse = CrawloraResponse<ModelSofascoreTeamPlayersResponseDoc>;
export interface SofascoreTeamPlayersParams {
  "id": string;
}

export type SofascoreTournamentSeasonsResponse = CrawloraResponse<ModelSofascoreTournamentSeasonsResponseDoc>;
export interface SofascoreTournamentSeasonsParams {
  "id": string;
}

export interface SofascoreService {
  event<T = SofascoreEventResponse>(params: SofascoreEventParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  eventH2h<T = SofascoreEventH2hResponse>(params: SofascoreEventH2hParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  eventIncidents<T = SofascoreEventIncidentsResponse>(params: SofascoreEventIncidentsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  eventLineups<T = SofascoreEventLineupsResponse>(params: SofascoreEventLineupsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  eventOdds<T = SofascoreEventOddsResponse>(params: SofascoreEventOddsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  eventStatistics<T = SofascoreEventStatisticsResponse>(params: SofascoreEventStatisticsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  liveEvents<T = SofascoreLiveEventsResponse>(params: SofascoreLiveEventsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  player<T = SofascorePlayerResponse>(params: SofascorePlayerParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  roundEvents<T = SofascoreRoundEventsResponse>(params: SofascoreRoundEventsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = SofascoreSearchResponse>(params: SofascoreSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  standings<T = SofascoreStandingsResponse>(params: SofascoreStandingsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  team<T = SofascoreTeamResponse>(params: SofascoreTeamParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  teamEvents<T = SofascoreTeamEventsResponse>(params: SofascoreTeamEventsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  teamPlayers<T = SofascoreTeamPlayersResponse>(params: SofascoreTeamPlayersParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentSeasons<T = SofascoreTournamentSeasonsResponse>(params: SofascoreTournamentSeasonsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  sofascore: SofascoreService;
}

export interface OperationParamsMap {
  "sofascore-event": SofascoreEventParams;
  "sofascore-event-h2h": SofascoreEventH2hParams;
  "sofascore-event-incidents": SofascoreEventIncidentsParams;
  "sofascore-event-lineups": SofascoreEventLineupsParams;
  "sofascore-event-odds": SofascoreEventOddsParams;
  "sofascore-event-statistics": SofascoreEventStatisticsParams;
  "sofascore-live-events": SofascoreLiveEventsParams;
  "sofascore-player": SofascorePlayerParams;
  "sofascore-round-events": SofascoreRoundEventsParams;
  "sofascore-search": SofascoreSearchParams;
  "sofascore-standings": SofascoreStandingsParams;
  "sofascore-team": SofascoreTeamParams;
  "sofascore-team-events": SofascoreTeamEventsParams;
  "sofascore-team-players": SofascoreTeamPlayersParams;
  "sofascore-tournament-seasons": SofascoreTournamentSeasonsParams;
}

export interface OperationResponseMap {
  "sofascore-event": SofascoreEventResponse;
  "sofascore-event-h2h": SofascoreEventH2hResponse;
  "sofascore-event-incidents": SofascoreEventIncidentsResponse;
  "sofascore-event-lineups": SofascoreEventLineupsResponse;
  "sofascore-event-odds": SofascoreEventOddsResponse;
  "sofascore-event-statistics": SofascoreEventStatisticsResponse;
  "sofascore-live-events": SofascoreLiveEventsResponse;
  "sofascore-player": SofascorePlayerResponse;
  "sofascore-round-events": SofascoreRoundEventsResponse;
  "sofascore-search": SofascoreSearchResponse;
  "sofascore-standings": SofascoreStandingsResponse;
  "sofascore-team": SofascoreTeamResponse;
  "sofascore-team-events": SofascoreTeamEventsResponse;
  "sofascore-team-players": SofascoreTeamPlayersResponse;
  "sofascore-tournament-seasons": SofascoreTournamentSeasonsResponse;
}

export interface OperationRequiredParamsMap {
  "sofascore-event": true;
  "sofascore-event-h2h": true;
  "sofascore-event-incidents": true;
  "sofascore-event-lineups": true;
  "sofascore-event-odds": true;
  "sofascore-event-statistics": true;
  "sofascore-live-events": true;
  "sofascore-player": true;
  "sofascore-round-events": true;
  "sofascore-search": true;
  "sofascore-standings": true;
  "sofascore-team": true;
  "sofascore-team-events": true;
  "sofascore-team-players": true;
  "sofascore-tournament-seasons": true;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "sofascore-event"
  | "sofascore-event-h2h"
  | "sofascore-event-incidents"
  | "sofascore-event-lineups"
  | "sofascore-event-odds"
  | "sofascore-event-statistics"
  | "sofascore-live-events"
  | "sofascore-player"
  | "sofascore-round-events"
  | "sofascore-search"
  | "sofascore-standings"
  | "sofascore-team"
  | "sofascore-team-events"
  | "sofascore-team-players"
  | "sofascore-tournament-seasons";

export declare const OperationIds: Readonly<{
  SofascoreEvent: "sofascore-event";
  SofascoreEventH2h: "sofascore-event-h2h";
  SofascoreEventIncidents: "sofascore-event-incidents";
  SofascoreEventLineups: "sofascore-event-lineups";
  SofascoreEventOdds: "sofascore-event-odds";
  SofascoreEventStatistics: "sofascore-event-statistics";
  SofascoreLiveEvents: "sofascore-live-events";
  SofascorePlayer: "sofascore-player";
  SofascoreRoundEvents: "sofascore-round-events";
  SofascoreSearch: "sofascore-search";
  SofascoreStandings: "sofascore-standings";
  SofascoreTeam: "sofascore-team";
  SofascoreTeamEvents: "sofascore-team-events";
  SofascoreTeamPlayers: "sofascore-team-players";
  SofascoreTournamentSeasons: "sofascore-tournament-seasons";
}>;
