// Code generated by the Crawlora platform SDK generator. DO NOT EDIT.

package sofascore

import (
	"context"
	"sort"
)

type parameterDefinition struct {
	Name             string
	In               string
	Type             string
	CollectionFormat string
	Required         bool
	Enum             []string
}

type operationDefinition struct {
	Method      string
	Path        string
	PathParams  []string
	QueryParams []parameterDefinition
	Produces    []string
	Security    []string
}

var operations = map[string]operationDefinition{
	"sofascore-event":              operationDefinition{Method: "GET", Path: "/sofascore/event", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-event-h2h":          operationDefinition{Method: "GET", Path: "/sofascore/event-h2h", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-event-incidents":    operationDefinition{Method: "GET", Path: "/sofascore/event-incidents", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-event-lineups":      operationDefinition{Method: "GET", Path: "/sofascore/event-lineups", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-event-odds":         operationDefinition{Method: "GET", Path: "/sofascore/event-odds", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-event-statistics":   operationDefinition{Method: "GET", Path: "/sofascore/event-statistics", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-live-events":        operationDefinition{Method: "GET", Path: "/sofascore/live-events", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "sport", In: "query", Type: "string", Required: true, Enum: []string{"football", "basketball", "tennis"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-player":             operationDefinition{Method: "GET", Path: "/sofascore/player", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-round-events":       operationDefinition{Method: "GET", Path: "/sofascore/round-events", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "season", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "round", In: "query", Type: "integer", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-search":             operationDefinition{Method: "GET", Path: "/sofascore/search", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "q", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-standings":          operationDefinition{Method: "GET", Path: "/sofascore/standings", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "season", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "type", In: "query", Type: "string", Required: true, Enum: []string{"total", "home", "away"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-team":               operationDefinition{Method: "GET", Path: "/sofascore/team", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-team-events":        operationDefinition{Method: "GET", Path: "/sofascore/team-events", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "direction", In: "query", Type: "string", Required: true, Enum: []string{"next", "last"}}, parameterDefinition{Name: "page", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-team-players":       operationDefinition{Method: "GET", Path: "/sofascore/team-players", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"sofascore-tournament-seasons": operationDefinition{Method: "GET", Path: "/sofascore/tournament-seasons", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
}

// OperationCount reports how many selected-platform operations this module exposes.
const OperationCount = 15

// OperationIDs returns the selected operation IDs in stable sorted order.
func OperationIDs() []string {
	ids := make([]string, 0, len(operations))
	for id := range operations {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

// Event calls the sofascore-event operation.
func (c *Client) Event(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-event", params)
}

// EventH2h calls the sofascore-event-h2h operation.
func (c *Client) EventH2h(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-event-h2h", params)
}

// EventIncidents calls the sofascore-event-incidents operation.
func (c *Client) EventIncidents(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-event-incidents", params)
}

// EventLineups calls the sofascore-event-lineups operation.
func (c *Client) EventLineups(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-event-lineups", params)
}

// EventOdds calls the sofascore-event-odds operation.
func (c *Client) EventOdds(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-event-odds", params)
}

// EventStatistics calls the sofascore-event-statistics operation.
func (c *Client) EventStatistics(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-event-statistics", params)
}

// LiveEvents calls the sofascore-live-events operation.
func (c *Client) LiveEvents(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-live-events", params)
}

// Player calls the sofascore-player operation.
func (c *Client) Player(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-player", params)
}

// RoundEvents calls the sofascore-round-events operation.
func (c *Client) RoundEvents(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-round-events", params)
}

// Search calls the sofascore-search operation.
func (c *Client) Search(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-search", params)
}

// Standings calls the sofascore-standings operation.
func (c *Client) Standings(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-standings", params)
}

// Team calls the sofascore-team operation.
func (c *Client) Team(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-team", params)
}

// TeamEvents calls the sofascore-team-events operation.
func (c *Client) TeamEvents(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-team-events", params)
}

// TeamPlayers calls the sofascore-team-players operation.
func (c *Client) TeamPlayers(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-team-players", params)
}

// TournamentSeasons calls the sofascore-tournament-seasons operation.
func (c *Client) TournamentSeasons(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "sofascore-tournament-seasons", params)
}
